
-- Here's a fairly simple Player that will simply walk around and shoot at people sometimes.
-- This will give a good example on the useage of the Glaces. I will be refering them as Players throughout the code.

-- Just localizing some stuff 
local random = math.random

function tablelength(T)
	local count = 0
	for _ in pairs(T) do count = count + 1 end
	return count
end

-- This table is used for the loot lists 
local Loot = {
    ["item_ammo_357"]=true,
	["item_ammo_357_large"]=true,
	["item_ammo_ar2"]=true,
	["item_ammo_ar2_large"]=true,
	["item_ammo_ar2_altfire"]=true,
	["item_ammo_crossbow"]=true,
	["item_healthkit"]=true,
	["item_healthvial"]=true,
	["item_ammo_pistol"]=true,
	["item_ammo_pistol_large"]=true,
	["item_rpg_round"]=true,
	["item_box_buckshot"]=true,
	["item_ammo_smg1"]=true,
	["item_ammo_smg1_large"]=true,
	["item_ammo_smg1_grenade"]=true,
	["item_battery"]=true,
	["ammo_357"]=true,
	["ammo_crossbow"]=true,
	["ammo_glockclip"]=true,
	["ammo_9mmbox"]=true,
	["ammo_mp5clip"]=true,
	["ammo_mp5grenades"]=true,
	["ammo_rpgclip"]=true,
	["ammo_buckshot"]=true,
	["ammo_gaussclip"]=true,
}

local Taunts = {
	"bot/hes_dead.wav",
	"bot/hes_down.wav",
	"bot/got_him.wav", 
	"bot/dropped_him.wav", 
	"bot/killed_him.wav", 
	"bot/ruined_his_day.wav", 
	"bot/wasted_him.wav", 
	"bot/took_him_out.wav", 
	"bot/took_him_out2.wav", 
	"bot/took_him_down.wav", 
	"bot/made_him_cry.wav", 
	"bot/hes_broken.wav", 
	"bot/hes_done.wav",
	"bot/i_am_dangerous.wav",
	"bot/do_not_mess_with_me.wav",
	"bot/they_never_knew_what_hit_them.wav",
	"bot/thats_the_way_this_is_done.wav",
	"bot/and_thats_how_its_done.wav",
	"bot/owned.wav",
	"bot/yesss.wav",
	"bot/yesss2.wav",
	"bot/yea_baby.wav",
	"bot/whoo.wav",
	"bot/whoo2.wav",
	"bot/oh_yea.wav",
	"bot/oh_yea2.wav",
	"bot/this_is_my_house.wav",
	"bot/i_got_more_where_that_came_from.wav",
	"bot/i_am_on_fire.wav",
	"bot/look_out_brag.wav",
	"bot/thats_right.wav",
	"bot/we_owned_them.wav",
	"bot/they_never_knew_what_hit_them.wav",
}

local Helps = {
	"bot/taking_fire_need_assistance2.wav",
	"bot/i_could_use_some_help.wav", 
	"bot/i_could_use_some_help_over_here.wav", 
	"bot/help.wav", 
	"bot/need_help.wav", 
	"bot/need_help2.wav", 
	"bot/im_in_trouble.wav"
}

local twoofthem = {
	"bot/two_of_them.wav.wav",
}

local oneguy = {
	"bot/one_guy.wav",
}


local threeofthem = {
	"bot/three.wav",
	"bot/three_of_them.wav",
}

local lotsofthem = {
	"bot/a_bunch_of_them.wav",
	"bot/theyre_all_over_the_place2.wav",
	"bot/theyre_everywhere2.wav",
	"bot/theres_too_many_of_them.wav",
	"bot/theres_too_many.wav",
	"bot/too_many2.wav",
	"bot/the_actions_hot_here.wav", 
	"bot/its_a_party.wav",
}

local Death = {
	"bot/pain2.wav",
	"bot/pain4.wav",
	"bot/pain5.wav",
	"bot/pain8.wav",
	"bot/pain9.wav",
	"bot/pain10.wav",
}

local Engage = {
	"bot/attacking.wav", 
	"bot/attacking_enemies.wav", 
	"bot/engaging_enemies.wav", 
	"bot/in_combat.wav", 
	"bot/in_combat2.wav", 
	"bot/returning_fire.wav" 
}

local FriendPain = {
	"bot/cut_it_out.wav",
	"bot/what_are_you_doing.wav",
	"bot/stop_it.wav",
	"bot/ow_its_me.wav",
	"bot/ow.wav",
	"bot/ouch.wav",
	"bot/im_on_your_side.wav",
	"bot/hold_your_fire.wav",
	"bot/hey.wav",
	"bot/hey2.wav",
}

local Pain = {
	"bot/ow.wav",
	"bot/ouch.wav",
}

local Long_guns = {
	"weapon_ar2",
	"weapon_357",
	"weapon_pistol",
	"weapon_crossbow",
	"weapon_rpg",
	"weapon_smg1",
	"weapon_357_hl1",
	"weapon_crossbow_hl1",
	"weapon_glock_hl1",
	"weapon_egon",
	"weapon_hornetgun",
	"weapon_mp5_hl1",
	"weapon_rpg_hl1",
	"weapon_gauss",
}

local Short_guns = {
	"weapon_shotgun",
	"weapon_frag",
	"weapon_handgrenade",
	"weapon_snark",
	"weapon_shotgun_hl1",
}

local melee = {
	"weapon_crowbar",
	"weapon_stunstick",
	"weapon_crowbar_hl1",
	"weapon_fists",
}

local AllEnemies = {
	["npc_cscanner"]=true,
	["CombineElite"]=true,
	["npc_combine_s"]=true,
	["npc_hunter"]=true,
	["npc_manhack"]=true,
	["npc_metropolice"]=true,
	["CombinePrison"]=true,
	["PrisonShotgunner"]=true,
	["npc_clawscanner"]=true,
	["ShotgunSoldier"]=true,
	["npc_stalker"]=true,
	["monster_alien_grunt"]=true,
	["monster_alien_slave"]=true,
	["monster_human_assassin"]=true,
	["monster_babycrab"]=true,
	["monster_bullchicken"]=true,
	["monster_alien_controller"]=true,
	["monster_bigmomma"]=true,
	["monster_human_grunt"]=true,
	["monster_headcrab"]=true,
	["monster_turret"]=true,
	["monster_houndeye"]=true,
	["monster_miniturret"]=true,
	["monster_sentry"]=true,
	["monster_zombie"]=true,
	["npc_antlion"]=true,
	["npc_antlionguard"]=true,
	["npc_antlionguardian"]=true,
	["npc_antlion_worker"]=true,
	["npc_barnacle"]=true,
	["npc_headcrab_fast"]=true,
	["npc_fastzombie"]=true,
	["npc_fastzombie_torso"]=true,
	["npc_headcrab"]=true,
	["npc_headcrab_black"]=true,
	["npc_poisonzombie"]=true,
	["npc_zombie"]=true,
	["npc_zombie_torso"]=true,
	["npc_zombine"]=true,
}

local names = {
    "Beta",
	"Generic Name 1",
	"Ze Uberman",
	"Q U A N T U M P H Y S I C S",
	"portable fridge",
	"Methman456",
	"i rdm kids for breakfast",
	"Cheese Adiction Therapist",
	"private hoovy",
	"Socks with Sandals",
	"Solar",
	"AdamYeBoi",
	"troll",
	"de_struction and de_fuse",
	"de_rumble",
	"decoymail",
	"Damian",
	"BrandontheREDSpy",
	"Braun",
	"brent13",
	"BrokentoothMarch",
	"BruH",
	"BudLightVirus",
	"Call of Putis",
	"CanadianBeaver",
	"Cake brainer",
	"cant scream in space",
	"CaptGravyBoness",
	"CaraKing09",
	"CarbonTugboat",
	"CastHalo",
	"cate",
	"ccdrago56",
	"cduncan05",
	"Chancellor_Ant",
	"Changthunderwang",
	"Charstorms",
	"Ch33kCLaper69",
	"Get Good Get Lmao Box",
	"Atomic",
	"Audrey",
	"Auxometer",
	"A Wise Author",
	"Awtrey516",
	"Aytx",
	"BabaBooey",
	"BackAlleyDealerMan",
	"BalieyeatsPizza",
	"ballzackmonster",
	"Banovinski",
	"bardochib",
	"BBaluka",
	"Bean man",
	"Bear",
	"Bearman_18",
	"beeflover100",
	"Albeon Stormhammer",
	"Andromedus",
	"Anilog",
	"Animus",
	"Sorry_an_Error_has_Occurred",
	"I am the Spy",
	"engineer gaming",
	"Ze Uberman",
	"Regret",
	"Sora",
	"Sky",
	"Scarf",
	"Graves",
	"bruh moment",
	"Garrys Mod employee",
	"i havent eaten in 69 days",
	"DOORSTUCK89",
	"PickUp That Can Cop",
	"Never gonna give you up",
	"if you are reading this, ur mom gay ",
	"The Lemon Arsonist",
	"Cave Johnson",
	"Chad",
	"Speedy",
	"Alan",
	"Jeremy The Scout",
	"Jane Doe",
	"Tavish Finnegan DeGroot",
	"Mikhail Weapons Guy",
	"Dell Conagher",
	"Ludwig Humboldt",
	"Mr. Mundy",
	"Miss Pauling",
	"Blutarch Mann",
	"Redmond Mann",
	"Gray Mann",
	"Olivia Mann",
	"Director",
	"Zhanna",
	"Yana",
	"Abraham Lincoln",
	"George Washington",
	"Franklin D. Roosevelt",
	"Niels Bohr",
	"Albert Einstein",
	"Amodeo Avogadro",
	"Anders Angstrom",
	"Andre Ampere",
	"Andrew D. Huxley",
	"Benjamin Franklin",
	"Blaise Pascal",
	"Christian Doppler",
	"Daniel Bernoulli",
	"Enrico Fermi",
	"Ernst Mach",
	"Erwin Schrodinger",
	"Freeman Dyson",
	"Galileo Galilei",
	"Gaspard Coriolis",
	"Georg Ohm",
	"Issac Newton",
	"James Maxwell",
	"James Joule",
	"Johannes Kepler",
	"Joseph Louis Lagrange",
	"Leonardo DaVinci",
	"Leonhard Euler",
	"Marie Curie",
	"Pierre Curie",
	"Max Planck",
	"Michael Faraday",
	"Nicolaus Copernicus",
	"Nikola Tesla",
	"Paul Dirac",
	"Rene Descartes",
	"Richard Feynman",
	"Robert Oppenheimer",
	"Stephen Hawking",
	"Werner Heisenberg",
	"Merasmus",
	"Wheatley",
	"I want nachos",
	"I like you",
	"You like me",
	"Your pet turtle",
	"You smell nice",
	"You smell bad",
	"You smell decent",
	"You smell adequate",
	"You smell exceptional",
	"I'm real",
	"I hate you",
	"I love you",
	"Let's make children",
	"Your stupid",
	"Mr.Banana",
	"Potatoman",
	"Vitamin C",
	"Enjoying the respawn?",
	"A hacker",
	"Bob the Builder.",
	"Did you miss me?",
	"You ded.",
	"Sandvich make me strong.",
	"Onion.",
	"Trade Me",
	"Jesus",
	"Devil",
	"God",
	"I'm Naked",
	"Necklace of human ears",
	"Your mother.",
	"Your father.",
	"Your grandfather.",
	"Your grandmother.",
	"Your brother-in-law.",
	"Your sister-in-law.",
	"Your sister.",
	"Your brother.",
	"Your son.",
	"Your daughter.",
	"Your uncle.",
	"Your aunt.",
	"Your ex.",
	"Your wife.",
	"Your husband.",
	"This is a bucket",
	"Dear god",
	"There's more",
	"No",
	"Wanna do it?",
	"SEDUCE ME",
	"I TELEPORTED BREAD",
	"WE ARE GOING TO LIVE FOREVER",
	"Booty",
	"I wish I was real.",
	"Seriously?",
	"You suck.",
	"I'm better than you.",
	"Robin Walker",
	"Gabe Newell",
	"Terminator",
	"That one guy from highskool",
	"Banana nut",
	"Artificial Intelligence",
	"W+M1 takes skill",
	"You tried.",
	"Pantscada",
	"Ruby",
	"Weiss",
	"Blake",
	"Yang",
	"Jaune",
	"Sarge",
	"Donut",
	"Rollins",
	"Ziggler",
	"Dakota",
	"Fandango",
	"Cena",
	"Bryan",
	"Paige",
	"Kairi",
	"Admiral",
	"Dapper",
	"Newsie",
	"French",
	"Boss",
	"Flower",
	"The Fez",
	"Mon",
	"Fancy",
	"Pimpy",
	"Bandito",
	"Word",
	"Lyfe",
	"La Rey",
	"Joker",
	"Honey",
	"Safe T",
	"Silent",
	"Big Dawg",
	"Joe",
	"Heli-Topper",
	"Emerald",
	"You",
	"Biscuit",
	"Cox",
	"Heart",
	"McElroy",
	"Raven",
	"Cinder",
	"Jake",
	"Finn",
	"Bubblegum",
	"Marceline",
	"Simon",
	"Peppermint",
	"Gunter",
	"BMO",
	"Lemongrab",
	"Rainicorn",
	"Michael",
	"Gavin",
	"Ray",
	"Geoff",
	"Jeremy",
	"Jack",
	"Ryan",
	"Miku",
	"Rin",
	"Len",
	"Prii",
	"Rusev",
	"Mei",
	"Garnet",
	"Amethyst",
	"Dana",
	"Ember",
	"Becky",
	"Ambrose",
	"Reigns",
	"Squigly",
	"Zone",
	"Jill",
	"Dorothy",
	"*Kira* Miki",
	"Stella",
	"Sei",
	"Fore",
	"Anna",
	"Abigail",
	"Garoad",
	"Porter",
	"Clicktman",
	"Dante",
	"Hardy",
	"Nakamura",
	"Styles",
	"Ryder",
	"Balor",
	"Strowman",
	"Samus",
	"Sheik",
	"Falcon",
	"Pikachu",
	"Kirby",
	"Inkling",
	"Octoling",
	"Amitie",
	"Witch",
	"Knife",
	"Marie",
	"Marina",
	"Pearl",
	"Coeur de Pirate",
	"Snake",
	"Kirk",
	"Spock",
	"Picard",
	"Scotty",
	"Uhura",
	"xxxx2345545",
	"qwe51",
	"e151",
	"2e31",
	"3e345",
	"ewe123",
	"Kara",
	"Illana",
	"Kira",
	"Barak",
	"Royal soveit",
	"SuperHero",
	"DENGGO290",
	"xaldin | trade.tf",
	"Nightus",
	"Darknightmarewolf",
	"Yukari Akiyama",
	"cake :3",
	"LMAO",
	"TiTaniumTurd",
	"2655684893",
	"Poichie blw.tf",
	"ViPer",
	"Komomimi",
	"Sir Blockingtone",
	"Nate",
	"giraFFe",
	"uniqueid",
	"My name is Zak Bagans",
	"mickrave0329",
	"MKrap",
	"It's a Lie",
	"Scout_BONK123!!!",
	"Soldat",
	"Ladic",
	"smile!",
	"Only 7 cm",
	"Tiny Desk Engineer",
	"MrMuskyHusky",
	"ImBoosted",
	"PanzerKommandant|8thPanzer",
	"johnzeus19",
	"Dunnionringz",
	"The Helper",
	"annajnavarro",
	"Lévi",
	"Fat Whale",
	"God HATES you!",
	"vintige kratskrag",
	"Who?",
	"Demoman Takes Skill!",
	"DohnJoe",
	"Santa Claus Schoolgirl",
	"Botulism Betty",
	"Straight from botnames.txt!",
	"Blessed To Moonwalk",
	"Chris P. Bacon",
	"Consume your Calcium",
	"rubbedsaltwound",
	"Content Quality Control",
	"SpamCracker",
	"Alcohol + Poor Life Decisions",
	"salad",
	"i dont sleep",
	"Kritty Kat",
	"Headshot!",
	"Mini-Biscuits Rights Activist.",
	"I'm not gay but $20 is $20",
	"Dr. Mantis Toboggan",
	"The Buttstaber",
	"2 FAST 4 U",
	"The Living Lawn Mower ",
	"Don't Fuckle With Shuckle",
	"Yolo Swaggins",
	"Suppository Breadcrumbs",
	"The Inhuman Scorch",
	"Honey I healed the Heavy",
	"Drinking + Driving",
	"spicy comments",
	"The Terrible Spicy Tea",
	"Thomas the Wank Engine",
	"Special Needs Engineer",
	"A Strange Festive Newt Gingrich",
	"A Sexually Attractive Cactus",
	"Swaghetti Yolonaise",
	"butt soup ",
	"Alcoholic Fat Guy",
	"Afraid Egg",
	"It's Legal in Japan",
	"I'm So Meta Even This Acronym.",
	"Unusual Foppish Boner",
	"Awkward Cuddle Boner",
	"A Distinctive lack of YOU!",
	"The Spanish Inquisition",
	"A Duck On Quack",
	"obesity related illness.",
	"ASS PANCAKES!",
	"Bodyshots Johnson",
	"Nein Lives.",
	"Dispenser (Target Practice)",
	"Country-Steak:Sauce",
	"Sock Full of Shame",
	"An overdose of French Toast",
	"One Kawaii MotherFucker",
	"Smokey Joe",
	"The Spicy Meatball.",
	"I Eat Toddlers",
	"Cunning Linguist",
	"3DayOldTeleportedBread",
	"Replay",
	"The Intense Hoovy Main",
	"?",
	"About_30_ninjas",
	"Ithoughtshewaslvl18 ",
	"404 GF not found  ",
	"IfIDiedIWasAFK ",
	"Jimmies Rustler",
	"go gadget aimbot ",
	"Neil Intergalactic Grandpa",
	"General Steiner",
	"Crazy Dewfus",
	"Sympatriotic",
	"doge",
	"Warmachine",
	"Diarrhea On Wheels",
	"Roasty my Toasty",
	"Steve Handjobs",
	"the hottest cheeto ever man",
	"Imagine actually dying to WM1",
	"Vince makes you say Shamwow",
	"PyrosAreAssholes",
	"Hilarious Bread",
	"poo c",
	"19 year old virgin",
	"Parasitic watermelon",
	"Welcome to Costco",
	"Sick Marmalade Grandpa",
	"buttsaggington",
	"Mother Fucking Oedipus",
	"I wonder what cum taste likes",
	"Money Hoes and Spaghetti-O's",
	"Mister Lister the Sister Fister",
	"Jonk",
	"Diet Cocaine",
	"Suspiciously Slow Scout",
	"Space Gandhi",
	"urine for a treat",
	"Delusional Arsonist",
	"Yung Micheal",
	"Old Man of America",
	"Spam & Heals Inc.",
	"yes_u_suck",
	"I_YELL_ALOT",
	"DroolTool",
	"A very fat man named Minh",
	"heavy from team fortress 5",
	"Cheesus Evangelionist",
	"Just a noob",
	"WetHitter",
	"Unsubscribe",
	"WeThePizza",
	"LactoseTheIntolerant",
	"MagicLOL",
	"getVACburned",
	"BeatdownMachine",
	"Such_A_Noob",
	"Balloonicorn",
	"Phosuphi",
	"BeardNoMore",
	"CutthroatChicken",
	"YourNameOnMySword",
	"BarryMcKackiner",
	"MyAxeYourFace",
	"Bagelofdeath",
	"Window Maker",
	"Rock8Man",
	"UsedFood",
	"beepbeepimajeep",
	"bitpull ",
	"PatMaximum",
	"you snoze you loze",
	"I_fap_twohanded",
	"DixonCider",
	"NoChildSupport",
	"Don't Shoot I'm a virgin ",
	"Pvt. Parts ",
	"BigD_McGee ",
	"McD'sHashbrown ",
	"SnackBitesWillRule ",
	"Stalin's Organ.",
	"BadUsernameSince2015",
	"NoDadNotTheBelt",
	"BrokenBoneBroker",
	"DontTouchThat",
	"InfinityLag",
	"NullPointer ",
	"FrankTheCrank",
	"Mexican't ",
	"HouseOfChards",
	"Playing GMod on A Toaster",
	"noob",
	"SpawnOfChaos",
	"I'm a Nokia ",
	"Solid Steak",
	"Killavanilla",
	"Tactical Toast",
	"OmgMyNameWontFi ",
	"Does you has? ",
	"niche one ",
	"he ded lol",
	"Testicular Thorsion ",
	"you_sun_of_a_beach ",
	"that's DOCTOR noob 4u ",
	"hoehoehoe",
	"PonySlaystation ",
	"suck my clock",
	"Muffled Fart ",
	"ClickSwitch",
	"GarbageRubberBand",
	"PennyUnwise",
	"Kacktus ",
	"Propanetankhank ",
	"HeyimGey. ",
	"Lol a shaved donkey",
	"De_stroyed",
	"i h8 myself",
	"eisoptrophobia.",
	"Respect your mom",
	"I wish i was dead",
	"CakeStealer",
	"KinosaurusRex",
	"Maximus",
	"SpyCrab",
	"MassTenderizer",
	"ParrotGal75",
	"Mentlegen Terrorist",
	"La Baguette Faguette",
	"Soup Can",
	"Lewdest Robot",
	"Hella Thicc",
	"Foot Lover Berry",
	"Hell is NOT okay",
	"unnamed",
	"Player",
	"HereComesThePainTrain",
	"lololol",
	"Nope.avi",
	"Snipping Tool",
	"Fax Machine",
	"m0tiVACation",
	"Just a Cardboard Box",
	"xXDark_LordXx",
	"expee",
	"????????",
	"nWord",
	"NotAnEngineer",
	"KidFromSchool",
	"Phone",
	"OmqItswOOdy",
	"canon father",
	"dart invader",
	"FreeeeeIpad",
	"nonuts",
	"E",
	"Carl Johnson",
	"Big Smoke",
	"CritsAreFair",
	"A Commie",
	"Prankster_Gangster",
	"Dad",
	"im going to area51",
	"AliveFace",
	"CornCakes",
	"Morgan",
	"goD",
	"Scunts_Sux",
	"Bruh231",
	"nikolai.thegamer 2019",
	"Pixels",
	"Mark",
	"Jon",
	"Garfield",
	"a pay 2 play",
	"a free 2 play",
	"yeet",
	"ESP",
	"a bunch of 0s and 1s",
	"Hitscan",
	"LmaoBox",
	"I DIE !",
	"Barny",
	"Gordon Freeman",
	"Drunken Wretch",
	"No",
	"IDontHaveAName",
	"PewDiePie",
	"Water Sheep",
	"Sandvich",
	"Mega dumboon",
	"MetalLegend",
	"A girl",
	"LessCrits",
	"Mario",
	"Loogi",
	"Sven",
	"Joergen",
	"'Merica fok ye",
	"Serbia",
	"Fonsi",
	"Despacito",
	"Pussy Memes",
	"Hail",
	"Bird",
	"SuperNatural",
	"SomeBruh",
	"This Guy",
	"Soulfull",
	"Undead",
	"Vehicle",
	"210Hill",
	"Bush-Dog",
	"The Wall",
	"The Bitch",
	"FishFace",
	"BFG 9000",
	"Bushman",
	"LucksMan",
	"Totally a human",
	"Shadows",
	"Nuclear Fruitcake",
	"Gold Steel",
	"scooteroni",
	"Mr.Poot",
	"liveMeat",
	"TalkyFan",
	"miss appauling",
	"Blue Man",
	"Red Man",
	"Gray Man",
	"Oblivious Man",
	"Rebel",
	"Havana OOONANA",
	"superguy",
	"Abraham da great",
	"George chopdowninnocenttree",
	"Franklin Deez nutz",
	"a wizard",
	"What",
	"thats nacho cheeze",
	"lesbian",
	"Gay",
	"papa Pete",
	"SpookyMint",
	"keegasp00ks",
	"Shock",
	"Im happy :D",
	"Im Sad D:",
	"Dead Meme",
	"Kohan-Kun",
	"Juan",
	"Chunky Joe",
	"Slyblindfox",
	"Trump",
	"Ronald",
	"Kortex",
	"Kim Jack Off",
	"Aimlocked",
	"KloGuy",
	"Chucky",
	"Volcano",
	"Doge Mint",
	"JackTheRipper",
	"Just a Cardboard Box",
	"~Erim~",
	"muesli",
	"Saiko",
	"aoihitsuji",
	"Reayr1",
	"Mekako",
	"ddaydeath",
	"Str00kerX",
	"Yuki",
	"Rena.",
	"cOnFuSeD",
	"terminator YD",
	"Kylin",
	"Seki",
	"Osmund",
	"Botulism Betty",
	"miyuki",
	"Pway",
	"TKO | gag0!",
	"Styx",
	"/sng/",
	"OWO",
	"Kr@zZy",
	"c0rsair",
	"nexcor",
	"pr3st0",
	"663",
	"V0id",
	"Killing Frenzy",
	"Campers Death",
	"You make me Laugh",
	"killaura",
	"Violently Happy",
	"Make my Day",
	"Pissed Off",
	"Bloodlust",
	"b02fof",
	"Zap!",
	"Dredd",
	"Fuzzey",
	"Bucus",
	"mokku",
	"A Professional With Standards",
	"Archimedes!",
	"Glorified Toaster with Legs",
	"Yana",
	"Your pet turtle",
	"You smell bad",
	"You smell nice",
	"I'm real",
	"Let's make children",
	"chen y",
	"NotDuckie",
	"De_stroyed",
	"nabongS",
	"h8 exam",
	"Crazii",
	"i h8 myself",
	"jowak1n",
	"beyluta",
	"natty_the_great",
	"ernest_aj",
	"bored",
	"hambug | buying skins",
	"Kiwino",
	"farn",
	"hezzy",
	"misty :3",
	"taFFy",
	"Kei",
	"I love you",
	"Sasucky",
	"eisoptrophobia.",
	"Yzui",
	"VKDrummer",
	"GDliZy",
	"Schizo x.O",
	"Yowza",
	"Hikari",
	"Niltf",
	"Kiruh",
	"caKuma",
	"Inkou PM",
	"I wish i was dead",
	"iamsleepless",
	"Hackyou",
	"Sokiy",
	"Kairu",
	"hatihati",
	"tarumaru",
	"berthe",
	"MB295",
	"Jumo",
	"kirkimedes",
	"Souless",
	"LamZee",
	"Aya-Chan",
	"gvek",
	"El Jägermeister",
	"ikitakunai",
	"Meti ",
	"VyLenT",
	"AlesTA",
	"Remi",
	"FTruby",
	"Touka_",
	"henkyyi",
	"Nitrogen09",
	"moyazou",
	"chamaji",
	"ramjam18",
	"VyYui",
	"tsumiki",
	"__dd",
	"Jushy",
	"TANUKANA",
	"Aeyonna | loving you hurts",
	"Alux.",
	"Young Jager",
	"Exhausted Life",
	"A E S T H E T I C",
	"Thomas_",
	"Ross Scarlet",
	"sonamed",
	"kuben",
	"Loord",
	"pasha",
	"Neo",
	"GoodRifle",
	"alex",
	"xF",
	"tb",
	"karl",
	"Virgo",
	"Savage",
	"rita",
	"prom1se",
	"xiaoe",
	"karrigan",
	"ArcadioN",
	"Friis",
	"wazorN",
	"suraNga",
	"minet",
	"j$",
	"zonic H$",
	"trace",
	"ave",
	"Sunde ACEEE",
	"Maximus",
	"Snappi",
	"xone",
	"luffeb",
	"katulen",
	"Strangelet",
	"AllThatGlitters21",
	"BreakingNYC",
	"DancingCrazy351",
	"Darkrogue20",
	"davedays",
	"DieAussenseiter",
	"DragonCharlz",
	"eddysson86",
	"ef12striker",
	"EllesGlitterGossip",
	"esmeedenters",
	"HeadsUpLisa | Lwoosers",
	"hotforwords",
	"Düktor",
	"IntelExtremeMasters",
	"Monarch5150",
	"mouzmovie",
	"LUlyuo",
	"NCIXcom",
	"RayWilliamJohnson",
	"RubberRoss ",
	"seductioncoach",
	"septinho",
	"soundlyawake",
	"Blacklegion104 ",
	"ICANHAZHEADSHOT ",
	"so4p | Lwoosers",
	"gg_legol4s3rZ7",
	"Dert",
	"HDstarcraft ",
	"Husky",
	"h0N123",
	"Da-MiGhtY 4357",
	"NetManiac",
	"Kyu >3<",
	">PartiZan<",
	"K!110grAmm",
	"SchtandartenFuhrer",
	"mu1ti-K!ll",
	"=ZL0Y=",
	"HeadKilla ==(oo)=>",
	"dub",
	"Kara",
	"Mechano!d",
	"3v!LKilla",
	"viz0r",
	"MiXa",
	"DiGGeR",
	"=GRoMoZeKA=",
	"ZveroBoy",
	"ahl.",
	"bds.",
	"brunk",
	"ElemenT",
	"fisker",
	"goseY",
	"Potti",
	"Morda",
	"n0name| S>Keys B>Knives",
	"NiTron",
	"Normal Human",
	"xXSniper_MainXx",
	"Left Foot In",
	"Right Foot Out",
	"Left Handed",
	"Calcium",
	"Dinnerbone",
	"Terrible Terror",
	"Shoot Me",
	"Aquatic Mammal",
	"Poopy Joe",
	"Free Stuff?",
	"Needs More Salt",
	"Duck Feet",
	"Impossibly Epic",
	"Joe Mamma",
	"Catapult of Pain",
	"Drunk and Scottish",
	"Half Life 3",
	"The Last Chip",
	"A Professional With Standards",
	"AimBot",
	"AmNot",
	"Aperture Science Prototype XR7",
	"Archimedes!",
	"BeepBeepBoop",
	"Big Mean Muther Hubbard",
	"Black Mesa",
	"BoomerBile",
	"Cannon Fodder",
	"CEDA",
	"Chell",
	"Chucklenuts",
	"Companion Cube",
	"Crazed Gunman",
	"CreditToTeam",
	"CRITRAWKETS",
	"Crowbar",
	"CryBaby",
	"CrySomeMore",
	"C++",
	"DeadHead",
	"Delicious Cake",
	"Divide by Zero",
	"Dog",
	"Force of Nature",
	"Freakin' Unbelievable",
	"Gentlemanne of Leisure",
	"GENTLE MANNE of LEISURE",
	"GLaDOS",
	"Glorified Toaster with Legs",
	"Grim Bloody Fable",
	"GutsAndGlory!",
	"Hat-Wearing MAN",
	"Headful of Eyeballs",
	"Herr Doktor",
	"HI THERE",
	"Hostage",
	"Humans Are Weak",
	"H@XX0RZ",
	"I LIVE!",
	"It's Filthy in There!",
	"IvanTheSpaceBiker",
	"Kaboom!",
	"Kill Me",
	"LOS",
	"Maggot",
	"Mann Co.",
	"Me",
	"Mega Baboon",
	"Mentlegen",
	"Mindless Electrons",
	"MoreGun",
	"Nobody",
	"Nom",
	"NotMe",
	"Numnutz",
	"One-Man Cheeseburger Apocalypse",
	"Poopy Joe",
	"Pow!",
	"RageQuit",
	"Ribs Grow Back",
	"Saxton Hale",
	"Screamin' Eagles",
	"SMELLY UNFORTUNATE",
	"SomeDude",
	"Someone Else",
	"Soulless",
	"Still Alive",
	"TAAAAANK!",
	"Target Practice",
	"ThatGuy",
	"The Administrator",
	"The Combine",
	"The Freeman",
	"The G-Man",
	"THEM",
	"Tiny Baby Man",
	"Totally Not A Bot",
	"trigger_hurt",
	"WITCH",
	"ZAWMBEEZ",
	"Ze Ubermensch",
	"Zepheniah Mann",
	"0xDEADBEEF",
	"10001011101",
	"John Spartan",
	"Leeloo Dallas Multipass",
	"Sho'nuff",
	"CAN YOUUUUUUUUU DIG IT?!?!?!?!",
	"Big Gulp Huh?",
	"Stupid Hot Dog",
	"I'm your huckleberry",
	"The Crocketeer",
	"Twitter dot com",
	"Turning dead",
	"sum",
	"Weed cat",
	"Mug Root Beer",
	"My mOm",
	"Kris Kross Applesauce",
	"I need a Medic bag!!!",
	"Based Kleiner",
	"The Real Zeta Player",
	"Beta",
	"Generic Name 1",
	"Ze Uberman",
	"Q U A N T U M P H Y S I C S",
	"portable fridge",
	"Methman456",
	"i rdm kids for breakfast",
	"Cheese Adiction Therapist",
	"private hoovy",
	"Socks with Sandals",
	"Solar",
	"AdamYeBoi",
	"troll",
	"de_struction and de_fuse",
	"de_rumble",
	"decoymail",
	"Damian",
	"BrandontheREDSpy",
	"Braun",
	"brent13",
	"BrokentoothMarch",
	"BruH",
	"BudLightVirus",
	"Call of Putis",
	"CanadianBeaver",
	"Cake brainer",
	"cant scream in space",
	"CaptGravyBoness",
	"CaraKing09",
	"CarbonTugboat",
	"CastHalo",
	"cate",
	"ccdrago56",
	"cduncan05",
	"Chancellor_Ant",
	"Changthunderwang",
	"Charstorms",
	"Ch33kCLaper69",
	"Get Good Get Lmao Box",
	"Atomic",
	"Audrey",
	"Auxometer",
	"A Wise Author",
	"Awtrey516",
	"Aytx",
	"BabaBooey",
	"BackAlleyDealerMan",
	"BalieyeatsPizza",
	"ballzackmonster",
	"Banovinski",
	"bardochib",
	"BBaluka",
	"Bean man",
	"Bear",
	"Bearman_18",
	"beeflover100",
	"Albeon Stormhammer",
	"Andromedus",
	"Anilog",
	"Animus",
	"Sorry_an_Error_has_Occurred",
	"I am the Spy",
	"engineer gaming",
	"Ze Uberman",
	"Regret",
	"Sora",
	"Sky",
	"Scarf",
	"Graves",
	"bruh moment",
	"Garrys Mod employee",
	"i havent eaten in 69 days",
	"DOORSTUCK89",
	"PickUp That Can Cop",
	"Never gonna give you up",
	"if you are reading this ur mom gay",
	"The Lemon Arsonist",
	"Cave Johnson",
	"Chad",
	"Speedy",
	"Alan",
	"Alpha",
	"Bravo",
	"Delta",
	"Charlie",
	"Echo",
	"Foxtrot",
	"Golf",
	"Hotel",
	"India",
	"Juliet",
	"Kilo",
	"Lima",
	"Lina",
	"Mike",
	"November",
	"Oscar",
	"Papa",
	"Quebec",
	"Romeo",
	"Sierra",
	"Tango",
	"Uniform",
	"Victor",
	"Whiskey",
	"X-Ray",
	"Yankee",
	"Zulu",
	"Flare",
	"Brian",
	"Frank",
	"Blaze",
	"Rin",
	"Bolt",
	"runthemingesarecoming",
	"Brute",
	"Snare",
	"Matt",
	"Arc",
	"VeeVee",
	"Serv",
	"Manjaro",
	"Sentinal",
	"Night",
	"Cayde",
	"Ranger",
	"Coach",
	"Bob Ross",
	"Mossman",
	"Nova",
	"drop10kthisisamug2874",
	"NUCCCLLEEEEEOOOOOOON",
	"u mad",
	"TheAdminge",
	"Trace",
	"Kelly",
	"Marauder",
	"AVATAR",
	"Scout",
	"Mirage",
	"Spark",
	"Jolt",
	"Ghost",
	"Summer",
	"Breenisgay69",
	"Dr Breen",
	"Combino",
	"Beowulf",
	"Heavy Weapons Guy",
	"GodFather",
	"Cheaple",
	"Desmond the epic",
	"Despairaity",
	"Destroyer_V0",
	"Devout Buddhist",
	"DingoGorditas",
	"DiscoDodgeBall",
	"Doc Johnson",
	"Dogmeat Tactical Vest",
	"Dogboy",
	"D O I N K",
	"ThatMW2Squeaker",
	"EBOI BOI",
	"Condescending Idiot",
	"CoolColton947",
	"CordingWater6",
	"Cpt_Core",
	"Crofty",
	"Crusader",
	"Ctoycat",
	"Cyclops",
	"Daddy_Debuff",
	"dallas",
	"DaLocust56",
	"Danny DeVito",
	"DaNub2038",
	"DarkNinjaD",
	"DarthHighGround",
	"DarthOobleck",
	"Dassault Mirage 2000C",
	"Davidb16",
	"D4rp_b0y",
	"Ruzzk1y",
	"SanicYT948",
	"sanitter",
	"Sanity",
	"Schutzhund",
	"scipion34",
	"Scotty2Hotty",
	"Seltzer",
	"Senior Cangrejo",
	"sfingers02",
	"Sharkgoat",
	"SharkyShark",
	"Shawty Like A Melody",
	"sh00shyb0i",
	"ShrekYeeter69",
	"Shrubster",
	"SirSamTheMan",
	"skinny peen",
	"Skulleewag395",
	"SleepingWarkat",
	"Sleipnlr",
	"Small PP Man",
	"SmortSocks",
	"Snapsro94",
	"Snipeshot556",
	"Snoot",
	"remember_no_russian",
	"Res",
	"ricefouboi",
	"rickymicdoo",
	"Rigatoni",
	"Robo7988143",
	"Rocketeer097",
	"Rollinwind",
	"rolltide10032",
	"Rome12310",
	"rushbuild",
	"mason the numbers what do they mean",
	"onin ring",
	"0nyx",
	"oofiet",
	"Orlorin_Foolofatook26",
	"pablo",
	"Paft_Dunk",
	"Panther0706",
	"Patrick",
	"PD53",
	"Pedro",
	"Peel1",
	"PenaPVP",
	"Penguan",
	"pepegonzalez2006",
	"Pescaxo",
	"phatty",
	"Piard",
	"Pickles",
	"Pigeon",
	"PilotJames007",
	"Pilotlily",
	"Piratenkapitan",
	"PixelG",
	"planewithnocanards",
	"platypus429",
	"Plumpotato47",
	"PM Prayuth",
	"poop_sock6969",
	"PollutionDieingPlanet",
	"Popsicle-Biscuit",
	"portable fridge",
	"Potatogamer555",
	"Prinz Eugen007",
	"PrivateWings",
	"PuercoVolador",
	"Purple Toyota AE87",
	"Pyromaniac",
	"B",
	"Quacker The Ducker",
	"Quadrapuds",
	"Obama",
	"obamas-last-name",
	"Aria",
	"0nE",
	"FluffySkunkBoy",
	"John117",
	"Kanye Bear",
	"NASCAR FAN 48",
	"Nightengale537",
	"Painini",
	"picklface",
	"Slavic_Chicken",
	"Snoucher",
	"Special",
	"wheatly_crab",
	"Yuri Kuroyanagi",
	"Doof",
	"Doritos Toasted Corn Tortilla Chips",
	"Doubletimes",
	"Dragon",
	"Adrian",
	"Umbreon-Kun",
	"Vinny Vinesauce",
	"amogus",
	"sus",
	"sussy baka",
	"Mug root beer",
	"Lumphy",
	"fork p",
	"That Annoying Guide",
	"george brown",
	"Final",
	"Sanicthegamer",
	"nascarfan42_48",
	"TriweeklyMoth96",
	"Sensitive Femboy fox",
	"OWO",
	"UWU",
	"e621.net",
	"Go Nuts!",
	"Chucklefucks",
	"( ͡° ͜ʖ ͡°)",
	"Dumptruck pixar ass",
	"The Horde",
	"There will be bloodshead",
	"PETA",
	"The part were I kill you",
	"Tails says cringe",
	"AH! HE'S BRITISH!!!!",
	"BIG SHOT",
	"Mommy!!! Help Me!!!",
	"The Hero",
	"The Warrior",
	"The Rouge",
	"The Necromancer",
	"The True Hero",
	"I am the real garry!",
	"Garry",
	"Friendly",
	"Menu user",
	"Big ol log",
	"Omega",
	"Talking Ben",
	"Perry the Platapus!",
	"Lifts her tail",
	"Clutch",
	"Minecrap",
	"Niko",
	"Never gonna give you up",
	"Never gonna let you down",
	"Lugig",
	"Mario",
	"C4!",
	"Don't @ me.",
	"Marco!",
	"Polo!",
	"why my pp hurt",
	"i love memes",
	"69",
	"21",
	"42",
	"rawr xd *nuzzles u*",
	"tehehe ur so warm",
	"*notices ur bulge*",
	"owo what's this?",
	"my name jeff",
	"what is 1+1",
	"gg ez",
	"e",
	"get good get lmaobox",
	"anime is for gay",
	"xD",
	"this server sucks",
	"*cough*",
	"Nibbs",
	"Weapons are useless",
	"Donald Trump",
	"Jimbo Slice",
	"realDonaldJTrump",
	"Pinkie Trouble",
	"Cum in your ass",
	"Horny motherfucker",
	"Mildly Menacing Flower Pot",
	"Charles Nuttington",
	"John Zanus",
	"I'm still alive",
	"Traitor",
	"loser",
	"Nobody",
	"Beep Boop",
	"Maggot",
	"Starcraft",
	"real nbghserd",
	"my friend",
	"Akill7600",
	"Head Full of Eyeballs",
	"Hoovy",
	"Sandvich",
	"Little Tiny Baby Man",
	"Babies",
	"Entire Team",
	"Totally Not a Bot",
	"Sausage",
	"Sandstone",
	"Sonic Fan",
	"Headache",
	"mr spielburg",
	"god",
	"Flashing Deadeye",
	"Shadowysn",
	"channel four",
	"1v1 me m8",
	"Dweeb Power",
	"Mr. Rusty booty",
	"Noxious Tank",
	"Ewitt69",
	"Hike Munt",
	"Dame Fiery",
	"Miyah Sesbig",
	"Mike Hunt",
	"The Trashman",
	"Dinglebop",
	"Shrek",
	"Unstable Finger",
	"Small baby head",
	"Thicc boi",
	"booty Robber",
	"He",
	"that dude",
	"no one",
	"myself",
	"mean dood",
	"derriere smasher",
	"derriere pummeler",
	"The Exodus",
	"Biglong Shlongdong",
	"REEEEEeee",
	"Nate",
	"LoLzL3GIT",
	"Nicobot 6000",
	"Le Fuher Potato",
	"S.S. Potato",
	"Maxtron 5000",
	"Webber",
	"Wilson",
	"Willow",
	"your mom",
	"bigbootygirl420",
	"Garbage Day",
	"Defuser",
	"a dead dude",
	"I'm not a nerd",
	"I am a nerd",
	"Bingle Deblooper",
	"CRITRAWKETS",
	"trashman is spy",
	"Ben Dover",
	"Mike Literus",
	"Bringle Borp",
	"Zingle Dorf",
	"Bajingle Shmorf",
	"Ringle Morph",
	"Dinkleburg",
	"Timmy T.",
	"Turner",
	"Cavebob Spongeman",
	"Pomme",
	"Terre",
	"Ralsei",
	"Vintage Sandvich",
	"Pooty",
	"ERROR 404",
	"Сука Блядь",
	"Michael De Santa",
	"Potato",
	"John Cena",
	"CuteDogXD",
	"RIOT",
	"Chairdof Sitler",
	"Daddy",
	"Communist Manifesto",
	"You",
	"Yourself",
	"Daddy",
	"Pewdiepie",
	"Therealpewdiepie4321",
	"de_way",
	"Dead Meme",
	"Han Shot First",
	"Broseph Stalin",
	"Colonel Sanders",
	"Big Smoke",
	"Smig Boke",
	"Mohammad",
	"Literally Hitler",
	"xXxminecraftkidxXx",
	"Vladimir Pootis",
	"Achmed",
	"Medic",
	"Doug Dimmadome",
	"Dougsdale Dimmadome",
	"Berlock Shmomes",
	"Alyx Vance",
	"The cum sock",
	"Isaac Kleiner",
	"Dr. Wallace Breen",
	"Bot",
	"The G-Man",
	"Odessa Cubbage",
	"Eli Vance",
	"Father Grigori",
	"Judith Mossman",
	"Barney Calhoun",
	"American Soldier",
	"German Soldier",
	"GIGN",
	"Elite Crew",
	"Artic Avengers",
	"SEAL Team Six",
	"GSG-9",
	"SAS",
	"Phoenix Connexion",
	"Guerilla Warfare",
	"Art",
	"Sandro",
	"Vance",
	"Cohrt",
	"Civil Protection",
	"Chell",
	"Combine Soldier",
	"Combine Prison Guard",
	"Elite Combine Soldier",
	"Stripped Combine Soldier",
	"Zombie",
	"Fast Zombie",
	"Zombine",
	"Corpse",
	"Charple",
	"Skeleton",
	"Van",
	"Ted",
	"Joe",
	"Eric",
	"Mike",
	"Erdin",
	"Joey",
	"Kanisha",
	"Kim",
	"Chau",
	"Naomi",
	"Lakeetra",
	"Discord",
	"Duke Nukem",
	"Duke Fishron",
	"Moon Lord",
	"Sun Lord",
	"Death",
	"Finn the Human",
	"Jake the Dog",
	"PB",
	"FP",
	"BMO",
	"Ice King",
	"Eevee",
	"Sanio",
	"Sandra",
	"Feet Fetishes",
	"Burger King foot lettuce",
	"The King",
	"Ronald Mcdonald",
	"The Dragonborn",
	"The Dovahkiin",
	"Number 15",
	"Isaac",
	"Cain",
	"Judas",
	"Spyro",
	"Eater of worlds",
	"Devourer of Gods",
	"Consumer of Ass",
	"???",
	"!!!",
	"Sprigatito",
	"PragerU",
	"Clans men",
	"The KKK",
	"White Power!!!",
	"BLM",
	"Joycon Drift",
	"Michael Jackson",
	"Little mac",
	"Big mac",
	"Fanboy",
	"Chum-Chum",
	"Vaporeon",
	"Kirby",
	"Gumball",
	"Fuecoco",
	"MMod",
	"April 11 1954",
	"Wizard101",
	"Wizard102",
	"Dark Lord",
	"Soda Junkie",
	"They Hunger",
	"The Guide",
	"Lemons!!! EVIL",
	"No Hobo",
	"Stop! Hammer Time!",
	"Heart Breaker",
	"Heavy Metal",
	"I AM LOOT!",
	"Star Power",
	"Eye on You",
	"Worm Fodder",
	"Smashing Poppet!",
	"MasterMind",
	"Boned",
	"Get a Life",
	"BloodBath",
	"Completely Awesome",
	"Til Death...",
	"Pretty in Pink",
	"Champion",
	"We ride at dawn",
	"It's Over BFG 9000",
	"Paws Together",
	"A+++",
	"It's a sausage",
	"Silence is golden",
	"Hacker!",
	"Cad",
	"V is for Virgin",
	"Dark things",
	"KARMA!",
	"Water sports",
	"Deja vu",
	"101",
	"Chicken",
	"Spongebob",
	"Patrick",
	"Pickle Rick",
	"No, this is Patrick",
	"Screw you guys",
	"PayDay",
	"You died",
	"Kittens with Style",
	"I taste awesome",
	"Gift Grab",
	"Sven",
	"Peer Review",
	"Baptism by Fire",
	"I Fry",
	"I Refuse too die!",
	"Fore!",
	"CL0WND",
	"Fat Ninjia",
	"Midnight Rider",
	"Scout",
	"Soldier",
	"Pyro",
	"Demoman",
	"Heavy",
	"Engineer",
	"Medic",
	"Sniper",
	"Spy",
	"sus amgous",
	"The Killer",
	"Clawroline",
	"LEGO Yoda",
	"Hat Kid",
	"Penis Balls",
	"Nyan Cat",
	"The Loaf",
	"The 1631 Name",
	"Grumpy Cat",
	"Larry",
	"Bob",
	"Tit",
	"Pit People",
	"Pawned",
	"Counter-Strike",
	"Vee",
	"Kabbu",
	"Leif",
	"Chex Man",
	"Kreedz",
	"The Chosen One",
	"The Sole Survivor",
	"The Lone Wanderer",
	"The Courier",
	"The Marine",
	"The Pilot",
	"The Convict",
	"The Hunter",
	"The Robot",
	"The Bullet",
	"Dart Monkey",
	"Monke",
	"Susie",
	"Kris",
	"Crazy Machine",
	"Frisk",
	"Chara",
	"The Hunter",
	"The Priest",
	"The Lich",
	"Toriel",
	"Mettaton",
	"sans",
	"Papyrus",
	"Counter-Terrorist",
	"Terrorist",
	"Bidoof",
	"Bigoof",
	"77+33=100",
	"Goku",
	"James Bear",
	"Quaxly",
	"jojo",
	"Camo Undies",
	"Nate The Great",
	"Hehehehaw",
	"I ran out of Ideas",
	"SexHaver69420",
	"Gaymer",
	"Gamer",
	"The first Goomba",
	"Wait this isn't fornite",
	"Jellybean",
	"First Time?",
	"Trickster",
	"Grandma says hello",
	"Punching bag",
	"It's a trap!",
	"PC Gamer",
	"Steamed Hams",
	"Me and my sister F#%$@&",
	"Cuphead",
	"Mugman",
	"Cwitchy",
	"No comment",
	"PNGTuber",
	"You've Got To Be Kidding!",
	"Aqua Pura",
	"a medic bag",
	"Jarate",
	"Salazzle",
	"Wario",
	"Waluigi",
	"Freddy Kruger",
	"Averge Redditor",
	"Manton Schools",
	"Final Chance",
	"Yiffer.xyz",
	"FU",
	"Sexbound",
	"Mom found the cum sock",
	"Protogen",
	"Furry",
	"Anti-furry",
	"Teratophilia",
	"ifunny",
	"Google",
	"Peach",
	"SANIC",
	"New Kid",
	"Douchbag",
	"Up and Comer",
	"The Boss",
	"Ol' Buddy Ol' Pal",
	"Love the Bomb",
	"Blast Mastery",
	"Samurai",
	"Champion of gmod",
	"Double Down",
	"Blind Luck",
	"Lead Dealer",
	"Hardcore",
	"Wild Card",
	"All or Nothing",
	"Bernie Sanders",
	"Dallas",
	"Bumbo",
	"Quincy",
	"That's alot of Damage",
	"Watch those Ristrockets",
	"Second Chance",
	"Kitten Squad",
	"Oneshot",
	"The Great Southern Plantkill",
	"Like a Boss",
	"Bucket of Bolts",
	"Not the Bees!",
	"Jeepers Creepers",
	"Infinity +1",
	"Heliophobia",
	"Hey! Listen!",
	"Pitcher",
	"Amorous",
	"Edmund Mcmillen",
	"God is dead",
	"Mr. House",
	"Yes Man",
	"Cazador",
	"Genectics",
	"Virgin",
	"Chad",
	"Beans",
	"Hello your computer has virus",
	"Avg mj fan",
	"pee board",
	"Hungry for piss",
	"samsung girl",
	"bornana",
	"Prof. Oak",
	"Skinny penis",
	"Fruity Pinocchio",
	"Clipussi",
	"Hit & Run",
	"Talking Tom",
	"Twatter",
	"GameFreak",
	"Boner Police",
	"Nazeem",
	"Jellybenis",
	"Bepis",
	"Bunny",
	"Please_Dont_Shoot_Me!",
	"While_you_read_this_name_i_will_shoot_you.",
	"Happy_Chappie",
	"My_name_is_nameless",
	"SIR DEFUSE THE BOMB!",
	"Crazy_Gamer",
	"TURRET!",
	"I_forgot_my_name.",
	"I forgor",
	"Still_Alive",
	"FRIENDLY FIRE!",
	"Sir Harmless",
	"I have a strange name!",
	"Alright",
	"You Win!",
	"Here i am!",
	"A very unlucky expert bot!",
	"Im Friendly! Well i was...",
	"NEED BACKUP!",
	"Brainless",
	"My name is soo long",
	"By the time you have read this i probibly would of killed you but who knows.",
	"Why is this my name?",
	"Basher",
	"Smasher",
	"An_Expert_Bot_With_A_Bad_Aim",
	"Dr.Breen",
	"Eli Vance",
	"Barney",
	"Dr.Kleiner",
	"Alyx Vance",
	"Slasher",
	"CrAzY",
	"Dagger",
	"I__will_shoot_anything_that_moves",
	"BANG!",
	"I_see_you!",
	"Stone",
	"Metal",
	"Poison",
	"Hunter",
	"Acid",
	"Top_Secret_Bot",
	"Lava",
	"Nightmare",
	"Destroyer",
	"Nuclear_Bot",
	"Crusher",
	"HEADSHOT!",
	"EXTEMELY_Crazy_Bot",
	"ZAP!",
	"Bullet",
	"LaSeR",
	"Elite Murderer",
	"Precise Killer",
	"An_easy_bot_that_is_really_lucky",
	"Master Of Disaster",
	"ExPlOsIvE",
	"Void",
	"A bot who has installed cheats.",
	"Brain Remover",
	"Before you read this name you are dead",
	"Mossy Mellow",
	"Krazy Cleiner",
	"Barneen",
	"Happy_Buddy",
	"Mad Brain",
	"Dagger The Sneaky",
	"Not A Bot!",
	"The Smasher",
	"The Bot Name Is A Lie",
	"The Bot Name Is A Spy",
	"Don't Shoot Me!",
	"Just Another Player!",
	"Friendly Bot",
	"Brainless",
	"Very Rich Bot",
	"Crazy Gamer",
	"Amazing Bot",
	"Dangerus Bot With A Bad Aim",
	"E-R-R-O-R",
	"Achievement grabber",
	"I have a really long name!",
	"GORDON HELP!",
	"Basher!",
	"A human that runs on code",
	"I have a license to kill zombies!",
	"Just a normal bot",
	"Who are you looking at?",
	"A gamer who does not have a computer",
	"Zombie slayer",
	"I have a strange name!",
	"STRIDER!",
	"Stop looking at me!,",
	"Mario teaches cucking",
	"RageingPussies",
	"Pooptopia",
	"Wreck it Rhino",
	"Giant Douch",
	"Turd Sandwich",
	"Trolled!!",
	"GET DUNKED ON!!!",
	"tim",
	"sans",
	"Frisk",
	"Kris",
	"Brfxxccxxmnpcccclllmmnprxvclmnckssqlbb11116",
	"Kingmessiah",
	"Facebook",
	"South Park",
	"H",
	"Truck Nuts",
	"Golden Win",
	"Loop Blues",
	"bd1p",
	"AI",
	"Beep Boop MAGGOT!",
	"Sticky Balls",
	"Musky Balls",
	"The Deepest Sword!",
	"You came for me!",
	"(◕‿◕)╭∩╮",
	"( ͡~ ͜ʖ ͡°)",
	"( ͡° ͜ʖ ͡°)",
	"( ° ͜ʖ °)",
	"( ͠° ͟ʖ ͡°)",
	"(͠≖ ͜ʖ͠≖)",
	"ʕ ͡° ʖ̯ ͡°ʔ",
	"( ͡ʘ ͜ʖ ͡ʘ)",
	"( ͡° ᴥ ͡°)",
	"( ͡♥ ͜ʖ ͡♥)",
	"( ͡ ͡° ͜つ ͡͡° )",
	"(☭ ͜ʖ ☭)",
	"( ͡°╭͜ʖ╮ ͡°)",
	"┏(-_-)┛",
	"ᕙ(▀̿ĺ̯▀̿ ̿)ᕗ",
	"( ͡° ͜ʖ ͡°)╭∩╮",
	"[̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]",
	"(｢•-•)｢ ʷʱʸ?",
	"( ͡°( ͡° ͜ʖ( ͡° ͜ʖ ͡°)ʖ ͡°) ͡°)",
	"╲⎝⧹ ( ͡° ͜ʖ ͡°) ⎠╱",
	"(⌐□_□)",
	"╭( ๐_๐)╮",
	"[̲̅$̲̅(̲̅5̲̅)̲̅$̲̅]",
	"ε=ε=┏( ・＿・)┛",
	"( ͡° ͜ʖ├┬┴┬┴",
	"( ͡° ل͜ ͡°)",
	"╭∩╮(◣_◢)╭∩╮",
	"╭∩╮( ͡° ͜ʖ ͡°)╭∩╮",
	"( °□°) ︵ ┻━┻",
	"👉👌",
	"🍆🍩🛏",
	"8====D",
	"( ㅅ )",
	"( ͡° ͜ʖ ͡°)⊃▭ι═════ﺤ",
	"( ◥◣_◢◤ )=ε/̵͇̿̿/’̿̿ ̿ ̿ ̿ ̿ ̿",
	"( -_･) ︻デ═一 ▸",
	"━╤デ╦︻(▀̿̿Ĺ̯̿̿▀̿ ̿)",
	"٩( ^ᴗ^ )۶",
	"(¬_¬)ﾉ",
	"(。^_・)ノ",
	"(･ω･)b",
	"d(-_^)",
	"Is are suffering funny to you?",
	"POTUS",
	"Uh Oh Spaghetti O's",
	"Mushu",
	"Chad Skyrim Sex mod collector",
	"G A M E A T O N E F P S",
	"^I'm with stupid^",
	"Rude Buster",
	"Fluffy Boy!",
	"The Fluffy Boy is Here",
	"Ralsei Plush",
	"Niko Plush",
	"Mr. Sandbag",
	"Asriel",
	"Alphy's Personal AI Bot",
	"Artificial Intelligence",
	"Gamer Girl Bath Water",
	"METTATON",
	"Alphys",
	"Undyne",
	"Oshawott",
	"Snivy",
	"MOAB",
	"BFB",
	"My Name Is Nothing",
	"ZOMG",
	"BAD",
	"DDT",
	"Paragon",
	"Doc Micheal",
	"Poop consumer 69420",
	"Fuck",
	"Big oof",
	"Obama's last name",
	"You fricken twat",
	"Temmie",
	"GenShit",
	"Engineer Gaming",
	"usedpizza",
	"Minecraft Steve",
	"Sexy Roxy",
	"Spider Pig",
	"Buff Micky Mouse",
	"Chucklenuts",
	"CryBaby",
	"WITCH",
	"ThatGuy",
	"Still Alive",
	"Hat-Wearing MAN",
	"Me",
	"Numnutz",
	"H@XX0RZ",
	"The G-Man",
	"Chell",
	"The Combine",
	"Totally Not A Bot",
	"Pow!",
	"Zepheniah Mann",
	"THEM",
	"LOS LOS LOS",
	"10001011101",
	"DeadHead",
	"ZAWMBEEZ",
	"MindlessElectrons",
	"TAAAAANK!",
	"The Freeman",
	"Black Mesa",
	"Soulless",
	"CEDA",
	"BeepBeepBoop",
	"NotMe",
	"CreditToTeam",
	"BoomerBile",
	"Someone Else",
	"Mann Co.",
	"Dog",
	"Kaboom!",
	"AmNot",
	"0xDEADBEEF",
	"HI THERE",
	"SomeDude",
	"GLaDOS",
	"Hostage",
	"Headful of Eyeballs",
	"CrySomeMore",
	"Aperture Science Prototype XR7",
	"Humans Are Weak",
	"AimBot",
	"C++",
	"GutsAndGlory!",
	"Nobody",
	"Saxton Hale",
	"RageQuit",
	"Screamin' Eagles",
	"Ze Ubermensch",
	"Maggot",
	"CRITRAWKETS",
	"Herr Doktor",
	"Gentlemanne of Leisure",
	"Companion Cube",
	"Target Practice",
	"One-Man Cheeseburger Apocalypse",
	"Crowbar",
	"Delicious Cake",
	"IvanTheSpaceBiker",
	"I LIVE!",
	"Cannon Fodder",
	"trigger_hurt",
	"Nom Nom Nom",
	"Divide by Zero",
	"GENTLE MANNE of LEISURE",
	"MoreGun",
	"Tiny Baby Man",
	"Big Mean Muther Hubbard",
	"Force of Nature",
	"Crazed Gunman",
	"Grim Bloody Fable",
	"Poopy Joe",
	"A Professional With Standards",
	"Freakin' Unbelievable",
	"SMELLY UNFORTUNATE",
	"The Administrator",
	"Mentlegen",
	"Archimedes!",
	"Ribs Grow Back",
	"It's Filthy in There!",
	"Mega Baboon",
	"Kill Me",
	"Glorified Toaster with Legs",
	"Grayson Jilani Moroder",
	"Add Bot Support",
	"The S-Mart Battle Dude",
	"The Overwatch Bomber",
	"The TF2 Commando",
	"Vivi Hugh",
	"The Magician",
	"Burglar",
	"Missionary",
	"Dark Missionary",
	"Doom Boom",
	"Evil Baalgar",
	"Cave Boy",
	"Coney Island Disco Palace",
	"The Protagonist",
	"The Antagonist",
	"The Deuteragonist",
	"Mister Mondez",
	"Calamari Cousin",
	"Peppy",
	"Grant Samson",
	"Ophelia",
	"Woops!",
	"Jason Fly",
	"Neon Green Mean Machine",
	"Monkey Puncher",
	"Flynn Taggart",
	"Hot Pink Pinch",
	"The Master",
	"Bubby",
	"Team Fortress News Network",
	"Dr. Venture",
	"I AM ERROR",
	"Shooter Person",
	"Nostalgia Gamer",
	"60's Kid",
	"Joe Cool",
	"Simply Epic",
	"Dallas",
	"Big Bad Billy",
	"Murray",
	"Bread Teleporter",
	"Sam Stone",
	"Hoagie Lover",
	"Criminal Mastermind",
	"Birdwell",
	"noob",
	"Work-In-Progress",
	"The Shootist",
	"Liberty Valance",
	"G. Lestrade",
	"Dr. M",
	"Alyx",
	"Captain Dan",
	"Wombo Combo",
	"Doctor Keller",
	"Calhoun",
	"info_player_teamspawn",
	"Big Wrench",
	"Watch and Learn",
	"This Man Has No Class",
	"Thi Barrett",
	"Lorelei Chen",
	"Dimitri Paramo",
	"John Pietrovich",
	"Coach",
	"Cate Archer",
	"The Livid Gamer",
	"Wololo",
	"Muscles2Big4Sleeves",
	"Gray Mann",
	"Professional Ideas Guy",
	"Bloodseeker",
	"FeedingMid",
	"Techy",
	"Shallow Gravy",
	"Baked Normals",
	"PlayerKnown",
	"Dr. Girlfriend",
	"Mister Duffman",
	"Cortical Bones",
	"CoolHopsBuddy",
	"Quarter-Life",
	"ZeroSevenOhSix",
	"Major Archer",
	"E-Major",
	"E-Minor",
	"Coping Mechanism",
	"Deathmatch FireFighter",
	"Shitty Wizard",
	"Shambler",
	"StickTogetherTeam",
	"Throwing Smokes",
	"Grabbin' Pills",
	"Raining Zombie Pieces",
	"Dodge This",
	"Lovelace",
	"Slipgate Slapper",
	"Boggy B",
	"EveryStepOfTheWay",
	"RicochetFan2000",
	"Blast Processor",
	"Judith Mossman",
	"Slick",
	"Einstein",
	"Walter",
	"Luther",
	"Ogre Magi",
	"P-ThirtyEight",
	"Inspector Zenigata",
	"Chase Tracer",
	"EXCUSE ME!",
	"Medical Attention",
	"Thompson Johnson",
	"Trinomial Equation",
	"Opposing Force",
	"Blue Shift",
	"Condition Zero",
	"One Errant Twitch",
	"IT COULD EVEN BE-",
	"Darnold",
	"TwoRefined",
	"Seduce me!",
	"Sentry Buster",
	"Sad Gamer",
	"Ron Zertnert",
	"RocketLaunchGood",
	"Baby Genius",
	"Iceman",
	"Maverick",
	"Goose",
	"John Stalvorn",
	"Long Distance Voyager",
	"Clockwork Angel",
	"Off a Rail",
	"The Analog Kid",
	"One Horseman",
	"New World Man",
	"Katty Smithereens",
	"Goldfinger",
	"Massive Head",
	"Dies Another day",
	"Thunderball",
	"Only Lives Twice",
	"Dancing On The Moon",
	"Mezzoforte",
	"Goofy Goober",
	"Jobber",
	"Tactical Interventionist",
	"Another Old Hermit",
	"Ring of Fired",
	"Unhappy Returns",
	"A Cold Day in Hell",
	"Blood in the Water",
	"Blood Money",
	"Old Wounds",
	"The Naked and the Dead",
	"SHODAN",
	"HAL-9000",
	"Hamlin Hamlin McGill",
	"Nacho",
	"Woefully Underused",
	"Gorilla Gunman",
	"Yeah, I Hunt Yetis",
	"func_detail",
	"trigger_push",
	"ThingID 2006",
	"IDSPISPOPD",
	"Melody Crosswell",
	"Treasure Guy",
	"Arti",
	"First Story Window",
	"Movie Skeleton",
	"RillerTheDriller",
	"Employee of the Month",
	"Cake Doughy",
	"SORRY NO AUDIO",
	"Sirian Werebull",
	"Alaskan Bullworm",
	"Jim Power",
	"A Bunch of Baby Ducks",
	"Mordecai and The Rigbys",
	"WOOWEEWOOWEE",
	"Vic Morgan",
	"Mister Vile",
	"Hello, Gordon!",
	"F-Stop",
	"Beta Archaeologist",
	"WHAT I CANT HEAR YOU",
	"G.I.B. Division",
	"The Part Where He Kills You",
	"Assault Rifle Master",
	"Nerf Lightning Gun",
	"Buff Lightning Gun",
	"Veridis Quo",
	"Xylobone",
	"Unholy Trinity",
	"Dad's Nuke",
	"Orchid Eater",
	"The Third Force",
	"Rathbone",
	"Exile Vilify",
	"Suitcase Full of Pistols & Money",
	"Day Defeatist",
	"Queue Continuum",
	"FourStrengthFourStam",
	"Z-Fighter",
	"Johnny Tsunami",
	"Oxymoron",
	"The Nameless Nomad",
	"Recycled Garbage",
	"Ye Olde Mercenary",
	"High Strung",
	"HECU Operative",
	"Combine Overwatch",
	"Blood Loss Detected",
	"Morphine Administered",
	"Fast Zombie",
	"Poison Zombie",
	"Zombine",
	"Redmond Mann",
	"Blutarch Mann",
	"Scrumpy",
	"Fire in the Hole!",
	"Gunman Chronologist",
	"Hooligan",
	"Just A Prankster",
	"The Director",
	"Astronomical Odds",
	"Your Clone",
	"Nothing Ventured",
	"Nothing Gained",
	"Joe Lame",
	"Oil Spiller",
	"Steel Trapper",
	"Mecha Engine Enthusiast",
	"Gear Grinder",
	"Man of Two Cities",
	"Classless Individual",
	"Classful Individual",
	"-REDACTED-",
	"I Survived The Crate Depression!",
	"Road Warrior",
	"General Lemonhead",
	"Razorback Enthusiast",
	"Backstabbing Scumbag",
	"Scout's Ma",
	"New Zealand Scientist",
	"Joe Blow",
	"The Extinctionist",
	"Le Poisson",
	"Fine Dandy",
	"Medicinal Practicioner",
	"Joey Murders",
	"Unfinished Asteroid",
	"Hatless Individual",
	"Hatful Individual",
	"Successful Mannconomist",
	"The Hole on Mars",
	"Gertie Freemont",
	"Senor Cardgage",
	"Doctor No",
	"Rancho Relaxo",
	"Walking Carpet",
	"119th Bot",
	"Self-Made Bot",
	"Vintage Bot",
	"Strange Bot",
	"Unusual Bot",
	"Collector's Bot",
	"Gold Rush Gamer",
	"Self-Esteemed",
	"Pyromania Enthusiast",
	"Uber Addict",
	"Machine in the Mann",
	"Line Ender",
	"Young Deemo",
	"The Madcap",
	"Tundra Topper",
	"Punk with a Pomp",
	"Shutterbug",
	"Bullet Buzzer",
	"Fashionable Megalomaniac",
	"Deep Cover Operator",
	"Ticket Boy",
	"Bonus Duck",
	"Ye Olde Baker Boy",
	"Baseball Bill",
	"Gentle Manne",
	"Tyrant Without Helm",
	"Respectless Rubber Man",
	"Brigade Ben",
	"Glengarry Bonny",
	"Scotman Barring Stove Pipe",
	"Tough Guy",
	"Football Star",
	"Texas Slim",
	"Miner Without A Light",
	"Otolaryngologist",
	"Pickelhaube Enthusiast",
	"Ritzy Rick",
	"Panamanian Professional",
	"The Backbiter",
	"Another Camera Beard",
	"Man-Bird of Aberdeen",
	"HazMat Headcase",
	"The Pyrovisionist",
	"I may be stupid...",
	"Neon Annihilator",
	"Flying Guillotine",
	"Balloonibouncer",
	"Water Gator",
	"Hunter in the Darkness",
	"Epic Mann",
	"Freedom Feathers",
	"Beast from Below",
	"The Headtaker",
	"The Manneater",
	"Leisurely Beef",
	"Type-2 Battletoad",
	"Saucemaster Vinny",
	"Joel the Bard",
	"The Eleventh Civilian",
	"Reverend Rev",
	"Handsome Jeremy",
	"Shelley",
	"Lazy Game Enthusiast",
	"Richie the Technician",
	"Awooga Foods",
	"Graverobber",
	"Zany Zapper",
	"Pro Grammar",
	"Cynical Biscuit",
	"Undercooked Hot Dog",
	"Paste-Tooth",
	"Cookie Cat",
	"Audible Jungle",
	"The Fifth Pond",
	"AfterImage",
	"A Wad of Terrys",
	"Team Fortress Redux",
	"Master of Disguise",
	"Architecturally Correct",
	"Rogue Artificial Intelligence",
	"Clot Gunman",
	"Brain with Two Eyeballs",
	"FOV Slider",
	"Anti-Aliased Annihilator",
	"Guys Hey Fellas",
	"Popped Cornpops",
	"A Massive Pile of Ants",
	"A Massive Pile of Hats",
	"Emotional",
	"w00tman",
	"Sephyr",
	"MonkeyMan",
	"KickAss",
	"g0at",
	"ch33s3",
	"rob0tnik",
	"tehph3ar",
	"HiPinger",
	"n00b",
	"willy wonka",
	"moe",
	"ramb0",
	"badger-mushroom",
	"Cry-o",
	"friendly garg",
	"[Ja]Hugh[SS]",
	"kit fisto",
	"[m00]m1lk",
	"bleetch",
	"i-Five",
	"Wittle Mouse",
	"How is my cheating?",
	"b0rked",
	"Sn1pa",
	"lam3r",
	"Raaaaa",
	"Cheesehhhh",
	"Gen.MaC_carthur",
	"madmax2",
	"Fillmore",
	"Devoted Christian",
	"Wait, this isn't the chum bucket",
	"No, this is Patrick",
	"sup",
	"Dr. Docter",
	"busttor",
	"StarFrost",
	"Robocop",
	"Red Knight",
	"Blue Knight",
	"Yellow Knight",
	"Green Knight",
	"Friendly Scout",
	"Friendly Soldier",
	"Friendly Pyro",
	"Friendly Demoman",
	"Friendly Heavy",
	"Friendly Engineer",
	"Friendly Medic",
	"Friendly Sniper",
	"Friendly Spy",
	"Enemy Scout",
	"Enemy Soldier",
	"Enemy Pyro",
	"Enemy Demoman",
	"Enemy Heavy",
	"Enemy Engineer",
	"Enemy Medic",
	"Enemy Sniper",
	"Enemy Spy",
	"Henry Stickman",
	"Charles Calvin",
	"SpiderHeck",
	"Gordan Freeman",
	"Gorgeous Freeman",
	"BaBa is You",
	"Hat Kid",
	"Youtube",
	"Discord Moniator",
	"FemPyro",
	"Nazi Zombie",
	"Cuphead",
	"Mugman",
	"Cliffe",
	"Minh",
	"Crusher",
	"Garret",
	"Rock",
	"Shark",
	"Wolf",
	"Gunner",
	"Vitaliy",
	"Ridgway",
	"Steel",
	"Stone",
	"Arnold",
	"Brett",
	"Kurt",
	"Kyle",
	"Moe",
	"Quade",
	"Quintin",
	"Ringo",
	"Rip",
	"Zach",
	"Cory",
	"Quinn",
	"Seth",
	"Vinny",
	"Brian",
	"Chad",
	"Chet",
	"Gabe",
	"Hank",
	"Ivan",
	"Jim",
	"Joe",
	"John",
	"Tony",
	"Tyler",
	"Victor",
	"Vladimir",
	"Zane",
	"Zim",
	"Adrian",
	"Bank",
	"Brad",
	"Connor",
	"Dave",
	"Dan",
	"Derek",
	"Don",
	"Eric",
	"Erik",
	"Finn",
	"Jeff",
	"Kevin",
	"Reed",
	"Rick",
	"Ted",
	"Troy",
	"Wade",
	"Wayne",
	"Xander",
	"Xavier",
	"Adam",
	"Andy",
	"Chris",
	"Colin",
	"Dennis",
	"Doug",
	"Duffy",
	"Gary",
	"GaryGaryGary",
	"Grant",
	"Greg",
	"GregTheEgg",
	"Ian",
	"Jerry",
	"Jon",
	"Keith",
	"Mark",
	"Matt",
	"Mike",
	"Nate",
	"Paul",
	"Scott",
	"Steve",
	"Tom",
	"Yahn",
	"Alfred",
	"Bill",
	"Brandon",
	"Dean",
	"Dustin",
	"Ethan",
	"Harold",
	"Henry",
	"Irving",
	"Jason",
	"Jenssen",
	"Josh",
	"Martin",
	"Nick",
	"Norm",
	"Pat",
	"Perry",
	"Shawn",
	"Tim",
	"Will",
	"Wyatt",
	"Allen",
	"Bort",
	"Bert",
	"Blort",
	"Bob",
	"Cecil",
	"Clarence",
	"Elliot",
	"Elmer",
	"Erine",
	"Eugene",
	"Fergus",
	"Ferris",
	"Frank",
	"Frasier",
	"Fred",
	"George",
	"Graham",
	"Harvey",
	"Irwin",
	"Larry",
	"Lester",
	"Marvin",
	"Neil",
	"Niles",
	"Oliver",
	"Toby",
	"Ulric",
	"Ulysses",
	"Uri",
	"Waldo",
	"Wally",
	"Walt",
	"Wesley",
	"Yanni",
	"Yogi",
	"Yuri",
	"OG RADIO Cliffe",
	"mr microsoft",
	"N00trius",
	"chucklenuts",
	"The Gaben",
	"Shark",
	"gundem w1ng",
	"Piano stevenZ",
	"zorbot z3d",
	"xXxamiritexXx",
	"TITAN KennyS",
	"Kenny",
	"Cartman",
	"Stan",
	"Eric Cartman",
	"Stan Marsh",
	"Kenny McCormick",
	"Kyle broflovski",
	"Homer Simpson",
	"Marg Simpson",
	"Bart Simpson",
	"Maggy Simpson",
	"Lisa Simpson",
	"sumDUD",
	"isTHATaGERMAN",
	"holla dolla",
	"24 funny 25",
	"Mario Mario",
	"Luigi Mario",
	"Fat Moe",
	"DENZEL_CURRY",
	"HIKO NEO",
	"uhah SUH DUDe",
	"jerryTHEmouse",
	"xV3N0M_0N1x",
	"eViL_RabBit",
	"hadoodle",
	"the STALINATOR",
	"area51 RMEN",
	"trigger hurt",
	"Murk",
	"GOD BARDOLPH",
	"ANDERZ AND SEMMLER",
	"HONK IF YO CORNY",
	"Sticky Joe",
	"n8terS Det",
	"Ghetto Viking Apocalypse",
	"Tiki",
	"TomHanks",
	"Jinjuh",
	"sp00kydavid",
	"Howie Mandel",
	"HgzeNJA",
	"MisterFalls",
	"n0thing",
	"area51 mummy",
	"SL4L samAxe",
	"area51 peachesSFC",
	"titanic Swimteam",
	"7spooky",
	"xizt",
	"YURI",
	"BOT allu",
	"olofmeister",
	"Awdrocity",
	"GeT_RiGhT",
	"alex poultry",
	"Snuggles",
	"pashabiceps",
	"Edd 8",
	"Nutrius2003",
	"h0Od nOrb1t",
	"Bork0239",
	"adolfo",
	"The Eggening",
	"Shark Jr",
	"Jingles",
	"MDK Vindictive",
	"Donald Tr0mp",
	"Chen_",
	"Mr White",
	"Antitry",
	"PrK",
	"FNATIC jw",
	"h4x0r_FluShA",
	"L4NCING the GOOGLED",
	"nice try BARDY guy",
	"COOARRALL",
	"impulse_101right",
	"Troy",
	"not bruceWayne",
	"t0m",
	"TaZ Hard2Kill",
	"slmple",
	"guy",
	"ThrillCosby",
	"xaos",
	"A_NAL_R_APE_666",
	"KimJongNam",
	"McJugga",
	"Saturated Fat",
	"Dr Sponge",
	"Spongebob Squarepants",
	"Spongebob Gamerpants",
	"Sodomized EM",
	"Skiddish Deer",
	"flash Drive 30",
	"Bilbo tea baggins",
	"M3_T00",
	"c_plusplus",
	"STALIN dAYS",
	"critrawkets213",
	"Arb0t3r",
	"d34dh34d",
	"__Yalanch1__",
	"Planet_of_the_grapes",
	"JEAN_",
	"Yung Gud",
	"Serpa FL",
	"D33n",
	"bUr2t_f1r3",
	"CHASEDADDY",
	"lidquid",
	"sarPE",
	"disney Thumper",
	"Thumper in my pants",
	"AWP LONG",
	"WTF",
	"Diaper Rash",
	"shrekt delta",
	"Stop guys!",
	"Awesome Lobster",
	"roket reag",
	"Rocket league bot",
	"Apres",
	"d00dle",
	"skaaaole",
	"disney ABU",
	"ABU's",
	"Ron Jeremy",
	"Shaaaaaaaaawn",
	"Gkaraka_SG",
	"elo90",
	"Wyatt Hepner l0l",
	"not_a_b0t",
	"POW",
	"torgoat_pr0ctize",
	"Ubermensch",
	"unloyal garda employee",
	"FIIIIIRE",
	"J0loney",
	"TZUGARIS",
	"Misho",
	"javasurplus",
	"theHostage",
	"There's a present in my pants",
	"Filthy Frank Anime Hunter",
	"BEN Frasier",
	"The Fetish Monster",
	"I__LIVE",
	"HITHERE",
	"Literally Hitler",
	"Lamborgihni thristy",
	"_THENiles",
	"Olives Boomer Bile",
	"BOT_Opie",
	"sweet_ROLLZ",
	"Ulric_Stormcloak",
	"CanoonFod3r",
	"RUSHB",
	"Waldo whereRU",
	"WallE",
	"Walt disguy",
	"Wesley snipes",
	"Yanni_thesinger",
	"Yogi bear",
	"Yuri GET YOUR HEAD DOWN",
	"Peach's ???",
	"Quangdang Dingle",
	"Lester the Unlikely",
	"Abomasnow",
	"Abra",
	"Absol",
	"Accelgor",
	"Aegislash",
	"Aerodactyl",
	"Aggron",
	"Aipom",
	"Alakazam",
	"Alcremie",
	"Alomomola",
	"Altaria",
	"Amaura",
	"Ambipom",
	"Amoonguss",
	"Ampharos",
	"Anorith",
	"Appletun",
	"Applin",
	"Araquanid",
	"Arbok",
	"Arcanine",
	"Arceus",
	"Archen",
	"Archeops",
	"Arctovish",
	"Arctozolt",
	"Ariados",
	"Armaldo",
	"Aromatisse",
	"Aron",
	"Arrokuda",
	"Articuno",
	"Audino",
	"Aurorus",
	"Avalugg",
	"Axew",
	"Azelf",
	"Azumarill",
	"Azurill",
	"Bagon",
	"Baltoy",
	"Banette",
	"Barbaracle",
	"Barboach",
	"Barraskewda",
	"Basculegion",
	"Basculin",
	"Bastiodon",
	"Bayleef",
	"Beartic",
	"Beautifly",
	"Beedrill",
	"Beheeyem",
	"Beldum",
	"Bellossom",
	"Bellsprout",
	"Bergmite",
	"Bewear",
	"Bibarel",
	"Bidoof",
	"Binacle",
	"Bisharp",
	"Blacephalon",
	"Blastoise",
	"Blaziken",
	"Blipbug",
	"Blissey",
	"Blitzle",
	"Boldore",
	"Boltund",
	"Bonsly",
	"Bouffalant",
	"Bounsweet",
	"Braixen",
	"Braviary",
	"Breloom",
	"Brionne",
	"Bronzong",
	"Bronzor",
	"Bruxish",
	"Budew",
	"Buizel",
	"Bulbasaur",
	"Buneary",
	"Bunnelby",
	"Burmy",
	"Butterfree",
	"Buzzwole",
	"Cacnea",
	"Cacturne",
	"Calyrex",
	"Camerupt",
	"Carbink",
	"Carkol",
	"Carnivine",
	"Carracosta",
	"Carvanha",
	"Cascoon",
	"Castform",
	"Caterpie",
	"Celebi",
	"Celesteela",
	"Centiskorch",
	"Cetitan",
	"Chandelure",
	"Chansey",
	"Charizard",
	"Charjabug",
	"Charmander",
	"Charmeleon",
	"Chatot",
	"Cherrim",
	"Cherubi",
	"Chesnaught",
	"Chespin",
	"Chewtle",
	"Chikorita",
	"Chimchar",
	"Chimecho",
	"Chinchou",
	"Chingling",
	"Cinccino",
	"Cinderace",
	"Clamperl",
	"Clauncher",
	"Clawitzer",
	"Claydol",
	"Clefable",
	"Clefairy",
	"Cleffa",
	"Clobbopus",
	"Cloyster",
	"Coalossal",
	"Cobalion",
	"Cofagrigus",
	"Combee",
	"Combusken",
	"Comfey",
	"Conkeldurr",
	"Copperajah",
	"Corphish",
	"Corsola",
	"Corviknight",
	"Corvisquire",
	"Cosmoem",
	"Cosmog",
	"Cottonee",
	"Crabominable",
	"Crabrawler",
	"Cradily",
	"Cramorant",
	"Cranidos",
	"Crawdaunt",
	"Cresselia",
	"Croagunk",
	"Crobat",
	"Croconaw",
	"Crustle",
	"Cryogonal",
	"Cubchoo",
	"Cubone",
	"Cufant",
	"Cursola",
	"Cutiefly",
	"Cyndaquil",
	"Darkrai",
	"Darmanitan",
	"Dartrix",
	"Darumaka",
	"Decidueye",
	"Dedenne",
	"Deerling",
	"Deino",
	"Delcatty",
	"Delibird",
	"Delphox",
	"Deoxys",
	"Dewgong",
	"Dewott",
	"Dewpider",
	"Dhelmise",
	"Dialga",
	"Diancie",
	"Diggersby",
	"Diglett",
	"Ditto",
	"Dodrio",
	"Doduo",
	"Donphan",
	"Dottler",
	"Doublade",
	"Dracovish",
	"Dracozolt",
	"Dragalge",
	"Dragapult",
	"Dragonair",
	"Dragonite",
	"Drakloak",
	"Drampa",
	"Drapion",
	"Dratini",
	"Drednaw",
	"Dreepy",
	"Drifblim",
	"Drifloon",
	"Drilbur",
	"Drizzile",
	"Drowzee",
	"Druddigon",
	"Dubwool",
	"Ducklett",
	"Dugtrio",
	"Dunsparce",
	"Duosion",
	"Duraludon",
	"Durant",
	"Dusclops",
	"Dusknoir",
	"Duskull",
	"Dustox",
	"Dwebble",
	"Eelektrik",
	"Eelektross",
	"Eevee",
	"Eiscue",
	"Ekans",
	"Eldegoss",
	"Electabuzz",
	"Electivire",
	"Electrike",
	"Electrode",
	"Elekid",
	"Elgyem",
	"Emboar",
	"Emolga",
	"Empoleon",
	"Enamorus",
	"Entei",
	"Escavalier",
	"Espeon",
	"Espurr",
	"Eternatus",
	"Excadrill",
	"Exeggcute",
	"Exeggutor",
	"Exploud",
	"Falinks",
	"Farfetch'd",
	"Fearow",
	"Feebas",
	"Fennekin",
	"Feraligatr",
	"Ferroseed",
	"Ferrothorn",
	"Fidough",
	"Finneon",
	"Flaaffy",
	"Flabébé",
	"Flapple",
	"Flareon",
	"Fletchinder",
	"Fletchling",
	"Floatzel",
	"Floette",
	"Florges",
	"Flygon",
	"Fomantis",
	"Foongus",
	"Forretress",
	"Fraxure",
	"Frillish",
	"Froakie",
	"Frogadier",
	"Froslass",
	"Frosmoth",
	"Fuecoco",
	"Furfrou",
	"Furret",
	"Gabite",
	"Gallade",
	"Galvantula",
	"Garbodor",
	"Garchomp",
	"Gardevoir",
	"Gastly",
	"Gastrodon",
	"Genesect",
	"Gengar",
	"Geodude",
	"Gible",
	"Gigalith",
	"Girafarig",
	"Giratina",
	"Glaceon",
	"Glalie",
	"Glameow",
	"Glastrier",
	"Gligar",
	"Gliscor",
	"Gloom",
	"Gogoat",
	"Golbat",
	"Goldeen",
	"Golduck",
	"Golem",
	"Golett",
	"Golisopod",
	"Golurk",
	"Goodra",
	"Goomy",
	"Gorebyss",
	"Gossifleur",
	"Gothita",
	"Gothitelle",
	"Gothorita",
	"Gourgeist",
	"Granbull",
	"Grapploct",
	"Graveler",
	"Greedent",
	"Greninja",
	"Grimer",
	"Grimmsnarl",
	"Grookey",
	"Grotle",
	"Groudon",
	"Grovyle",
	"Growlithe",
	"Grubbin",
	"Grumpig",
	"Gulpin",
	"Gumshoos",
	"Gurdurr",
	"Guzzlord",
	"Gyarados",
	"Hakamo-o",
	"Happiny",
	"Hariyama",
	"Hatenna",
	"Hatterene",
	"Hattrem",
	"Haunter",
	"Hawlucha",
	"Haxorus",
	"Heatmor",
	"Heatran",
	"Heliolisk",
	"Helioptile",
	"Heracross",
	"Herdier",
	"Hippopotas",
	"Hippowdon",
	"Hitmonchan",
	"Hitmonlee",
	"Hitmontop",
	"Ho-Oh",
	"Honchkrow",
	"Honedge",
	"Hoopa",
	"Hoothoot",
	"Hoppip",
	"Horsea",
	"Houndoom",
	"Houndour",
	"Huntail",
	"Hydreigon",
	"Hypno",
	"Igglybuff",
	"Illumise",
	"Impidimp",
	"Incineroar",
	"Indeedee",
	"Infernape",
	"Inkay",
	"Inteleon",
	"Ivysaur",
	"Jangmo-o",
	"Jellicent",
	"Jigglypuff",
	"Jirachi",
	"Jolteon",
	"Joltik",
	"Jumpluff",
	"Jynx",
	"Kabuto",
	"Kabutops",
	"Kadabra",
	"Kakuna",
	"Kangaskhan",
	"Karrablast",
	"Kartana",
	"Kecleon",
	"Keldeo",
	"Kingdra",
	"Kingler",
	"Kirlia",
	"Klang",
	"Kleavor",
	"Klefki",
	"Klink",
	"Klinklang",
	"Koffing",
	"Komala",
	"Kommo-o",
	"Koraidon",
	"Krabby",
	"Kricketot",
	"Kricketune",
	"Krokorok",
	"Krookodile",
	"Kubfu",
	"Kyogre",
	"Kyurem",
	"Lairon",
	"Lampent",
	"Landorus",
	"Lanturn",
	"Lapras",
	"Larvesta",
	"Larvitar",
	"Latias",
	"Latios",
	"Leafeon",
	"Leavanny",
	"Lechonk",
	"Ledian",
	"Ledyba",
	"Lickilicky",
	"Lickitung",
	"Liepard",
	"Lileep",
	"Lilligant",
	"Lillipup",
	"Linoone",
	"Litleo",
	"Litten",
	"Litwick",
	"Lombre",
	"Lopunny",
	"Lotad",
	"Loudred",
	"Lucario",
	"Ludicolo",
	"Lugia",
	"Lumineon",
	"Lunala",
	"Lunatone",
	"Lurantis",
	"Luvdisc",
	"Luxio",
	"Luxray",
	"Lycanroc",
	"Machamp",
	"Machoke",
	"Machop",
	"Magby",
	"Magcargo",
	"Magearna",
	"Magikarp",
	"Magmar",
	"Magmortar",
	"Magnemite",
	"Magneton",
	"Magnezone",
	"Makuhita",
	"Malamar",
	"Mamoswine",
	"Manaphy",
	"Mandibuzz",
	"Manectric",
	"Mankey",
	"Mantine",
	"Mantyke",
	"Maractus",
	"Mareanie",
	"Mareep",
	"Marill",
	"Marowak",
	"Marshadow",
	"Marshtomp",
	"Masquerain",
	"Mawile",
	"Medicham",
	"Meditite",
	"Meganium",
	"Melmetal",
	"Meloetta",
	"Meltan",
	"Meowstic",
	"Meowth",
	"Mesprit",
	"Metagross",
	"Metang",
	"Metapod",
	"Mew",
	"Mewtwo",
	"Mienfoo",
	"Mienshao",
	"Mightyena",
	"Milcery",
	"Milotic",
	"Miltank",
	"Mime Jr.",
	"Mimikyu",
	"Minccino",
	"Minior",
	"Minun",
	"Miraidon",
	"Misdreavus",
	"Mismagius",
	"Moltres",
	"Monferno",
	"Morelull",
	"Morgrem",
	"Morpeko",
	"Mothim",
	"Mr. Mime",
	"Mr. Rime",
	"Mudbray",
	"Mudkip",
	"Mudsdale",
	"Muk",
	"Munchlax",
	"Munna",
	"Murkrow",
	"Musharna",
	"Naganadel",
	"Natu",
	"Necrozma",
	"Nickit",
	"Nidoking",
	"Nidoqueen",
	"Nidoran♀",
	"Nidoran♂",
	"Nidorina",
	"Nidorino",
	"Nihilego",
	"Nincada",
	"Ninetales",
	"Ninjask",
	"Noctowl",
	"Noibat",
	"Noivern",
	"Nosepass",
	"Numel",
	"Nuzleaf",
	"Obstagoon",
	"Octillery",
	"Oddish",
	"Omanyte",
	"Omastar",
	"Onix",
	"Oranguru",
	"Orbeetle",
	"Oricorio",
	"Oshawott",
	"Overqwil",
	"Pachirisu",
	"Palkia",
	"Palossand",
	"Palpitoad",
	"Pancham",
	"Pangoro",
	"Panpour",
	"Pansage",
	"Pansear",
	"Paras",
	"Parasect",
	"Passimian",
	"Patrat",
	"Pawmi",
	"Pawniard",
	"Pelipper",
	"Perrserker",
	"Persian",
	"Petilil",
	"Phanpy",
	"Phantump",
	"Pheromosa",
	"Phione",
	"Pichu",
	"Pidgeot",
	"Pidgeotto",
	"Pidgey",
	"Pidove",
	"Pignite",
	"Pikachu",
	"Pikipek",
	"Piloswine",
	"Pincurchin",
	"Pineco",
	"Pinsir",
	"Piplup",
	"Plusle",
	"Poipole",
	"Politoed",
	"Poliwag",
	"Poliwhirl",
	"Poliwrath",
	"Polteageist",
	"Ponyta",
	"Poochyena",
	"Popplio",
	"Porygon",
	"Porygon-Z",
	"Porygon",
	"Primarina",
	"Primeape",
	"Prinplup",
	"Probopass",
	"Psyduck",
	"Pumpkaboo",
	"Pupitar",
	"Purrloin",
	"Purugly",
	"Pyroar",
	"Pyukumuku",
	"Quagsire",
	"Quaxly",
	"Quilava",
	"Quilladin",
	"Qwilfish",
	"Raboot",
	"Raichu",
	"Raikou",
	"Ralts",
	"Rampardos",
	"Rapidash",
	"Raticate",
	"Rattata",
	"Rayquaza",
	"Regice",
	"Regidrago",
	"Regieleki",
	"Regigigas",
	"Regirock",
	"Registeel",
	"Relicanth",
	"Remoraid",
	"Reshiram",
	"Reuniclus",
	"Rhydon",
	"Rhyhorn",
	"Rhyperior",
	"Ribombee",
	"Rillaboom",
	"Riolu",
	"Rockruff",
	"Roggenrola",
	"Rolycoly",
	"Rookidee",
	"Roselia",
	"Roserade",
	"Rotom",
	"Rowlet",
	"Rufflet",
	"Runerigus",
	"Sableye",
	"Salamence",
	"Salandit",
	"Salazzle",
	"Samurott",
	"Sandaconda",
	"Sandile",
	"Sandshrew",
	"Sandslash",
	"Sandygast",
	"Sawk",
	"Sawsbuck",
	"Scatterbug",
	"Sceptile",
	"Scizor",
	"Scolipede",
	"Scorbunny",
	"Scrafty",
	"Scraggy",
	"Scyther",
	"Seadra",
	"Seaking",
	"Sealeo",
	"Seedot",
	"Seel",
	"Seismitoad",
	"Sentret",
	"Serperior",
	"Servine",
	"Seviper",
	"Sewaddle",
	"Sharpedo",
	"Shaymin",
	"Shedinja",
	"Shelgon",
	"Shellder",
	"Shellos",
	"Shelmet",
	"Shieldon",
	"Shiftry",
	"Shiinotic",
	"Shinx",
	"Shroomish",
	"Shuckle",
	"Shuppet",
	"Sigilyph",
	"Silcoon",
	"Silicobra",
	"Silvally",
	"Simipour",
	"Simisage",
	"Simisear",
	"Sinistea",
	"Sirfetch'd",
	"Sizzlipede",
	"Skarmory",
	"Skiddo",
	"Skiploom",
	"Skitty",
	"Skorupi",
	"Skrelp",
	"Skuntank",
	"Skwovet",
	"Slaking",
	"Slakoth",
	"Sliggoo",
	"Slowbro",
	"Slowking",
	"Slowpoke",
	"Slugma",
	"Slurpuff",
	"Smeargle",
	"Smoliv",
	"Smoochum",
	"Sneasel",
	"Sneasler",
	"Snivy",
	"Snom",
	"Snorlax",
	"Snorunt",
	"Snover",
	"Snubbull",
	"Sobble",
	"Solgaleo",
	"Solosis",
	"Solrock",
	"Spearow",
	"Spectrier",
	"Spewpa",
	"Spheal",
	"Spinarak",
	"Spinda",
	"Spiritomb",
	"Spoink",
	"Sprigatito",
	"Spritzee",
	"Squirtle",
	"Stakataka",
	"Stantler",
	"Staraptor",
	"Staravia",
	"Starly",
	"Starmie",
	"Staryu",
	"Steelix",
	"Steenee",
	"Stonjourner",
	"Stoutland",
	"Stufful",
	"Stunfisk",
	"Stunky",
	"Sudowoodo",
	"Suicune",
	"Sunflora",
	"Sunkern",
	"Surskit",
	"Swablu",
	"Swadloon",
	"Swalot",
	"Swampert",
	"Swanna",
	"Swellow",
	"Swinub",
	"Swirlix",
	"Swoobat",
	"Sylveon",
	"Taillow",
	"Talonflame",
	"Tangela",
	"Tangrowth",
	"Tapu Bulu",
	"Tapu Fini",
	"Tapu Koko",
	"Tapu Lele",
	"Tauros",
	"Teddiursa",
	"Tentacool",
	"Tentacruel",
	"Tepig",
	"Terrakion",
	"Thievul",
	"Throh",
	"Thundurus",
	"Thwackey",
	"Timburr",
	"Tirtouga",
	"Togedemaru",
	"Togekiss",
	"Togepi",
	"Togetic",
	"Torchic",
	"Torkoal",
	"Tornadus",
	"Torracat",
	"Torterra",
	"Totodile",
	"Toucannon",
	"Toxapex",
	"Toxel",
	"Toxicroak",
	"Toxtricity",
	"Tranquill",
	"Trapinch",
	"Treecko",
	"Trevenant",
	"Tropius",
	"Trubbish",
	"Trumbeak",
	"Tsareena",
	"Turtonator",
	"Turtwig",
	"Tympole",
	"Tynamo",
	"Type: Null",
	"Typhlosion",
	"Tyranitar",
	"Tyrantrum",
	"Tyrogue",
	"Tyrunt",
	"Umbreon",
	"Unfezant",
	"Unown",
	"Ursaluna",
	"Ursaring",
	"Urshifu",
	"Uxie",
	"Vanillish",
	"Vanillite",
	"Vanilluxe",
	"Vaporeon",
	"Venipede",
	"Venomoth",
	"Venonat",
	"Venusaur",
	"Vespiquen",
	"Vibrava",
	"Victini",
	"Victreebel",
	"Vigoroth",
	"Vikavolt",
	"Vileplume",
	"Virizion",
	"Vivillon",
	"Volbeat",
	"Volcanion",
	"Volcarona",
	"Voltorb",
	"Vullaby",
	"Vulpix",
	"Wailmer",
	"Wailord",
	"Walrein",
	"Wartortle",
	"Watchog",
	"Weavile",
	"Weedle",
	"Weepinbell",
	"Weezing",
	"Whimsicott",
	"Whirlipede",
	"Whiscash",
	"Whismur",
	"Wigglytuff",
	"Wimpod",
	"Wingull",
	"Wishiwashi",
	"Wobbuffet",
	"Woobat",
	"Wooloo",
	"Wooper",
	"Wormadam",
	"Wurmple",
	"Wynaut",
	"Wyrdeer",
	"Xatu",
	"Xerneas",
	"Xurkitree",
	"Yamask",
	"Yamper",
	"Yanma",
	"Yanmega",
	"Yungoos",
	"Yveltal",
	"Zacian",
	"Zamazenta",
	"Zangoose",
	"Zapdos",
	"Zarude",
	"Zebstrika",
	"Zekrom",
	"Zeraora",
	"Zigzagoon",
	"Zoroark",
	"Zorua",
	"Zubat",
	"Zweilous",
	"Zygarde",
	"Kid Named Finger",
	"Waltuh",
	"Better call Saul",
	"Hey cool ya found me",
	"I'm in your game now",
	":snig:",
	"That one guy who got banned for calling me a nerd or something",
	"This stuff took me a week lol",
	"Hope your having fun with us",
	":)",
	":(",
	">:(",
	"Basterd",
	"I'm with stupid -->",
	"Gotta love this long list of terrible names",
}

-- probably a better way to do random models, but I think this will work anyways
local models = {
    "models/player/alyx.mdl",
	"models/player/barney.mdl",
	"models/player/breen.mdl",
	"models/player/charple.mdl",
	"models/player/p2_chell.mdl",
	"models/player/combine_soldier.mdl",
	"models/player/combine_super_soldier.mdl",
	"models/player/combine_soldier_prisonguard.mdl",
	"models/player/corpse1.mdl",
	"models/player/arctic.mdl",
	"models/player/gasmask.mdl",
	"models/player/guerilla.mdl",
	"models/player/leet.mdl",
	"models/player/phoenix.mdl",
	"models/player/riot.mdl",
	"models/player/swat.mdl",
	"models/player/urban.mdl",
	"models/player/dod_american.mdl",
	"models/player/dod_german.mdl",
	"models/player/eli.mdl",
	"models/player/Group01/female_01.mdl",
	"models/player/Group01/female_02.mdl",
	"models/player/Group01/female_03.mdl",
	"models/player/Group01/female_03.mdl",
	"models/player/Group01/female_04.mdl",
	"models/player/Group01/female_05.mdl",
	"models/player/Group01/female_06.mdl",
	"models/player/Group03/female_01.mdl",
	"models/player/Group03/female_02.mdl",
	"models/player/Group03/female_03.mdl",
	"models/player/Group03/female_04.mdl",
	"models/player/Group03/female_05.mdl",
	"models/player/Group03/female_06.mdl",
	"models/player/gman_high.mdl",
	"models/player/hostage/hostage_01.mdl",
	"models/player/hostage/hostage_02.mdl",
	"models/player/hostage/hostage_03.mdl",
	"models/player/hostage/hostage_04.mdl",
	"models/player/kleiner.mdl",
	"models/player/magnusson.mdl",
	"models/player/Group01/male_01.mdl",
	"models/player/Group01/male_02.mdl",
	"models/player/Group01/male_03.mdl",
	"models/player/Group01/male_04.mdl",
	"models/player/Group01/male_05.mdl",
	"models/player/Group01/male_06.mdl",
	"models/player/Group01/male_07.mdl",
	"models/player/Group01/male_08.mdl",
	"models/player/Group01/male_09.mdl",
	"models/player/Group03/male_01.mdl",
	"models/player/Group03/male_02.mdl",
	"models/player/Group03/male_03.mdl",
	"models/player/Group03/male_04.mdl",
	"models/player/Group03/male_05.mdl",
	"models/player/Group03/male_06.mdl",
	"models/player/Group03/male_07.mdl",
	"models/player/Group03/male_08.mdl",
	"models/player/Group03/male_09.mdl",
	"models/player/Group03m/male_01.mdl",
	"models/player/Group03m/male_02.mdl",
	"models/player/Group03m/male_03.mdl",
	"models/player/Group03m/male_04.mdl",
	"models/player/Group03m/male_05.mdl",
	"models/player/Group03m/male_06.mdl",
	"models/player/Group03m/male_07.mdl",
	"models/player/Group03m/male_08.mdl",
	"models/player/Group03m/male_09.mdl",
	"models/player/Group03m/female_01.mdl",
	"models/player/Group03m/female_02.mdl",
	"models/player/Group03m/female_03.mdl",
	"models/player/Group03m/female_04.mdl",
	"models/player/Group03m/female_05.mdl",
	"models/player/Group03m/female_06.mdl",
	"models/player/monk.mdl",
	"models/player/mossman.mdl",
	"models/player/mossman_arctic.mdl",
	"models/player/odessa.mdl",
	"models/player/police.mdl",
	"models/player/police_fem.mdl",
	"models/player/Group02/male_02.mdl",
	"models/player/Group02/male_04.mdl",
	"models/player/Group02/male_06.mdl",
	"models/player/Group02/male_08.mdl",
	"models/player/skeleton.mdl",
	"models/player/soldier_stripped.mdl",
	"models/player/zombie_classic.mdl",
	"models/player/zombie_fast.mdl",
	"models/player/zombie_soldier.mdl",
}

CreateConVar( "glaceteambots_shouldfollow", 0, FCVAR_ARCHIVE, "If the bots should follow you around", 0, 1 )
CreateConVar( "glaceteambots_notalk", 0, FCVAR_ARCHIVE, "If the bots shouldn't talk in voice chat", 0, 1 )
CreateConVar( "glaceteambots_refresh", 0, FCVAR_ARCHIVE, "If the bots should kick themselves and rejoin on death", 0, 1 )

-- To start off, we encase the entire player in their own function to spawn them.
function SpawnTeamGlacePlayer()
    local ply = Glace_CreatePlayer( names[ random( #names ) ], models[ random( #models ) ], "GLACERANDOM" )
	--local has_talked = false

    if !IsValid( ply ) then print( "Unable to spawn player! Player limit may have been reached!" ) return end -- We need to make sure that we say this and end this function or else we get useless bug reports

    -- We now start making the AI

    ply:Glace_SetAutoReload( true )
    ply:Glace_SelectRandomWeapon()
    ply:Glace_SetThinkTime( 0.1 )
	local hasSwitchedm = false
	local hasSwitchedl = false
	local hasSwitcheds = false


    -- For this player, we'll create a form of State System to work with.
    -- We'll create a custom var and a few new functions for this specific Player.
    ply.Glace_State = "idle"
	ply.Attackcooldown = 0
	

    function ply:Glace_GetState() -- Returns the Glace_State
        return self.Glace_State
    end

    function ply:Glace_SetState( state ) -- Sets the state. We'll be using this to switch from a idle mode to a combat
        self.Glace_LastState = self.Glace_State
        self.Glace_State = state
    end

    function ply:Glace_GetLastState() -- Gets the last state the player was in
        return self.Glace_LastState
    end

    function ply:Glace_SetEnemy( ent ) -- Set the enemy
        self.Glace_Enemy = ent
    end

    function ply:Glace_GetEnemy() -- Get the enemy
        return self.Glace_Enemy
    end

	function ply:Glace_radio( radiotype )
        if self.LastTaunt && self.LastTaunt > CurTime() then return end
        if !self:Alive() then return end
		if GetConVar( "glaceteambots_notalk" ):GetBool(0) then return end
		
    
        --local talk = ( radiotype[ random( #radiotype ) ] )
        self:Glace_SaySoundFile( radiotype[ random( #radiotype ) ] )
    
        self.LastTaunt = CurTime() + 10
    end
	
	function ply:Glace_DoAttackthing()
	if CurTime() < ply.Attackcooldown then return end -- Do not run if we are still under a cooldown
		
		self:Glace_AddKeyPress( IN_ATTACK, false )
		self:Glace_AddKeyPress( IN_ATTACK2 )
	
	ply.Attackcooldown = CurTime() + 5 
	end

    function ply:Glace_OnKilled( attacker, inflictor )
		self:EmitSound( Death[ random( #Death ) ] )
		self:Glace_CancelMove() 
        self:Glace_SetEnemy( nil )
        self:Glace_SetState( "idle" )
		if GetConVar( "glaceteambots_refresh" ):GetBool(1) then
			self:Glace_Timer( 3, function() self:Kick() end)
			self:Glace_Timer( 3, function() RunConsoleCommand("glacebase_spawnteamplayer") end)
		else
			self:Glace_Timer( 3, function() self:Spawn() end)
			self:Glace_Timer( 3, function() self:Glace_SelectRandomWeapon() end)
		end
    end

    function ply:Glace_OnHurt( attacker, hp, damage ) -- Play a generic pain sound
		local friend = player.GetAll()
		local friend2
		
		for k, v in ipairs( friend ) do
			friend2 = v
			break
		end
		
		if attacker == friend2 then self:EmitSound( FriendPain[ random( #FriendPain ) ] ) return end
        if attacker == self then return end
		self:Glace_Face( attacker )
		self:EmitSound( Pain[ random( #Pain ) ] )
		self:Glace_CancelMove() 
        self:Glace_SetEnemy( attacker )
        self:Glace_SetState( "incombat" )
		if random(20) == 1 then
			self:Glace_radio( Helps )
		end
    end

    -- Now we create our normal Think hook
    function ply:Glace_Think()

        --[[if random(1000000) == 1 then -- funny 1 in a million song
            self:Glace_radio( "music/cossack_sandvich.wav" )
        end]]

        if self:Health() < self:GetMaxHealth()*0.4 and self:Glace_GetState() != "findmedkits" then -- I NEED A MEDIC BAG
			if GetConVar( "glaceteambots_shouldfollow" ):GetBool(1) then return end
            self:Glace_SetState("findmedkits")
            self:Glace_CancelMove()
        end

        if IsValid(self:GetActiveWeapon()) and !self:GetActiveWeapon():HasAmmo() then -- If we run out of ammo, then switch weapons
            self:Glace_SelectRandomWeapon()
        end

        if self:Glace_GetState() == "incombat" and !IsValid(self.Glace_Enemy) then -- If our enemy isn't valid then just go back to normal
            self:Glace_Sprint( false )
            self:Glace_StopFace()
            self:Glace_SetState( "idle" )
            self:Glace_SetEnemy(nil)
        end

        if IsValid( self.Glace_Enemy ) and self:Glace_CanSee( self.Glace_Enemy ) then -- Shoot at our target if we can see em

            self:Glace_AddKeyPress( IN_ATTACK )
			self:Glace_DoAttackthing()
            return 
        end -- If the enemy is valid then don't run the code below

        local surrounding = self:Glace_FindInSphere( 1500, function(ent) if IsValid(ent) and AllEnemies[ent:GetClass()] and ent:Alive() then return true end end ) -- Get Nearby NPCs and Players we can see
		
		if random(10) == 1 then
			if tablelength(surrounding) == 1 then
				self:Glace_radio( oneguy )
			end
			
			if tablelength(surrounding) == 2 then
				self:Glace_radio( twoofthem )
			end
			
			if tablelength(surrounding) == 3 then
				self:Glace_radio( threeofthem )
			end
			
			if tablelength(surrounding) >= 4 then
				self:Glace_radio( lotsofthem )
			end
		end
		
        for k, v in RandomPairs(surrounding) do -- Select a random target
			
            self:Glace_CancelMove() 
            self:Glace_SetEnemy( v )
            self:Glace_SetState( "incombat" )
            break
        end

    end

    -- This hook is the same as Nextbot's ENT:OnOtherKilled(). This will be called whenever a NPC, Nextbot, or Player that isn't us dies
    function ply:Glace_OnOtherKilled( victim, attacker, inflictor )
        if victim == self:Glace_GetEnemy() then
            self:Glace_Sprint( false )
            self:Glace_StopFace()
            self:Glace_SetState( "idle" )
            self:Glace_SetEnemy(nil)
			if random(10) == 1 then
				self:Glace_radio( Taunts )
			end
        end
    end
	
	function ply:Glace_OnStuck()
        GlaceBase_DebugPrint( "Player got stuck" )

        
        self:Glace_SetForwardMove( self:GetWalkSpeed() ) 

        self:Glace_AddKeyPress( IN_DUCK, true )
        self:Glace_AddKeyPress( IN_JUMP ) 


        self:Glace_Timer( 1, function()

            self:Glace_SetForwardMove() -- Stop the override movement
            self:Glace_AddKeyPress( IN_DUCK ) -- Releases the hold on the crouch key

        end, "crouchrelease", 1 )


        
        self:Glace_Timer( 0.5, function()

            
            self:Glace_CancelMove()

        end )
    end
	
    function ply:Glace_ThreadedThink() -- Same as Nextbot's ENT:RunBehaviour() except this is internally in a while true loop so it'll constantly run the function after it finishes the entire function
        
        if self:Glace_GetState() == "idle" then -- Idle state will just be wandering

            self:Glace_Sprint( true )
			--self:Glace_Timer( 15, function() has_talked = false end)
			self:Glace_Timer( 10, function() hasSwitchedm = false end)
			self:Glace_Timer( 10, function() hasSwitchedl = false end)
			self:Glace_Timer( 10, function() hasSwitcheds = false end)
			
			local pos = self:Glace_GetRandomPosition( 2000 ) -- Get a random spot that we want to go to
			local human = player.GetHumans()
			local surrounding = self:Glace_FindInSphere( 1500, function(ent) if Loot[ent:GetClass()] then return true end end ) 
            local ammo 

            for k, v in RandomPairs( surrounding ) do
                ammo = v
                break
            end
            

            if IsValid(ammo) then -- Go grab that ammo
                self:Glace_Sprint( true )
                self:Glace_StopFace()

                self:Glace_Timer( 0.4, function()
                    if !IsValid( ammo ) then return "remove" end
                    if self:Glace_GetRangeSquaredTo( ammo ) <= ( 200 * 200 ) then return "remove" end
                    if self:Glace_GetState() != "findammo" then return "remove" end
                    if self:GetVelocity():Length() < 200 then return end 
                     
    
                    self:Glace_AddKeyPress( IN_JUMP )
                end, "bhop", 30 ) 

                self:Glace_MoveToPos( ammo, nil, 10, 3, true )
            end
			if GetConVar( "glaceteambots_shouldfollow" ):GetBool(1) then
				for k, v in ipairs(human) do
					self:Glace_MoveToPos( v, nil, 250, nil, false) -- Follow the player
				end
			else
				self:Glace_MoveToPos( pos ) -- Go to that spot with the default args
			end
				

        elseif self:Glace_GetState() == "incombat" and IsValid( self:Glace_GetEnemy() ) then -- Combat State
			if random(10) == 1 then
				self:Glace_radio( Engage )
			end
			
			-- weapon switching code can probabley be done better, but I think it's ok
			local range = 160000
			local TargetDist = self:Glace_GetRangeSquaredTo( self:Glace_GetEnemy() )
			if (TargetDist < range/4 and TargetDist < range*2) and hasSwitchedm == false then
				for k, v in RandomPairs(melee) do
					if !self:GetWeapon( v ) then return end
					self:Glace_SwitchWeapon ( v )
					hasSwitchedm = true
					hasSwitchedl = false
					hasSwitcheds = false
				end
			elseif (TargetDist > range) and hasSwitchedl == false then
				for k, v in RandomPairs(Long_guns) do
					if !self:GetWeapon( v ) then return end
					self:Glace_SwitchWeapon ( v )
					hasSwitchedm = false
					hasSwitchedl = true
					hasSwitcheds = false
				end
			elseif (TargetDist < range) and hasSwitcheds == false then
				for k, v in RandomPairs(Short_guns) do
					if !self:GetWeapon( v ) then return end
					self:Glace_SwitchWeapon ( v )
					hasSwitchedm = false
					hasSwitchedl = false
					hasSwitcheds = true
				end
			end
			
            -- This timer makes the player bhop
            self:Glace_Timer( 0.4, function()
                if !IsValid( self:Glace_GetEnemy() ) then return "remove" end
                if self:Glace_GetRangeSquaredTo( self:Glace_GetEnemy() ) <= ( 200 * 200 ) then return "remove" end
                if self:Glace_GetState() != "incombat" then return "remove" end  -- We return "remove" so that the timer will remove itself so we don't have to do it. This will be pretty useful
                if self:GetVelocity():Length() < 200 then return end 
                

                self:Glace_AddKeyPress( IN_JUMP )
            end, "bhop", 30 ) 

            -- If we can't see our enemy, then go to their position
            local pos = self:Glace_CanSee( self:Glace_GetEnemy() ) and ( self:Glace_GetEnemy():GetPos() + self:Glace_GetNormalTo( self:Glace_GetEnemy() ) * -400 ) or self:Glace_GetEnemy():GetPos()

            self:Glace_Sprint( true )
            self:Glace_Face( self:Glace_GetEnemy() )
            self:Glace_MoveToPos( pos, nil, nil )

        elseif self:Glace_GetState() == "findmedkits" then -- Find a medkit or perish

            -- Only return medkits
            local surrounding = self:Glace_FindInSphere( 1500, function(ent) if ent:GetClass() == "item_healthkit" or ent:GetClass() == "item_healthvial" then return true end end ) 
            local medkit 

            for k, v in RandomPairs( surrounding ) do
                medkit = v
                break
            end
            
            if IsValid(medkit) then
                self:Glace_Sprint( true )
                self:Glace_StopFace()

                self:Glace_Timer( 0.4, function() -- Bhop to the medkit and pray the enemies never played CSGO for years
                    if !IsValid( medkit ) then return "remove" end
                    if self:Glace_GetRangeSquaredTo( medkit ) <= ( 200 * 200 ) then return "remove" end
                    if self:Glace_GetState() != "findmedkits" then return "remove" end
                    if self:GetVelocity():Length() < 200 then return end 
                     
    
                    self:Glace_AddKeyPress( IN_JUMP )
                end, "bhop", 30 ) 

                self:Glace_MoveToPos( medkit, nil, nil, 3, true ) -- Go to the medkit and have the pathfinder wait for the player
            end
            self:Glace_SetState( self:Glace_GetLastState() )
		end

    end

    

end


-- We now "register" the player as a console command so we can spawn them
concommand.Add("glacebase_spawnteamplayer",SpawnTeamGlacePlayer)